// بيانات العقود العشرة المُحدَّثة (نسخة استبدال كاملة) — رايه فودز
// مستخرجة من ملفات Word المرفقة بتاريخ 2026-07-27، وتم التحقق من تطابق مجموع كل جدول كميات مع الإجمالي المطبوع في العقد

export const CLIENT_DATA = {
  name: "رايه فودز",
  address: "66 ر 11 المنطقة الصناعية الأولى - مدينة السادات (تجميد وتعبئة المواد الغذائية)",
  notes: "سجل تجاري رقم 17002 استثمار القاهرة",
};

type BoqRow = { code: string; description: string; unit: string; quantity: number; unitPrice: number };

export type ContractSeed = {
  projectCode: string;
  projectName: string;
  contractNumber: string;
  signedDate: string;
  contractValue: number;
  advancePaymentPct: number;
  notes: string;
  boq: BoqRow[];
};

export const CONTRACTS_SEED_V2: ContractSeed[] = [
  {
    projectCode: "PRJ-ADMIN-FACADE",
    projectName: "إحلال وتجديد واجهة مبنى الإدارة",
    contractNumber: "CTR-ADMIN-FACADE-2026",
    signedDate: "2026-03-01",
    contractValue: 1524950.0,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "بالمقطوعية إزالة الجرافياتو والبياض المفكك والبند يشمل السقالات وكل ما يلزم لنهو الأعمال", unit: "مقطوعية", quantity: 1.0, unitPrice: 17000.0 },
      { code: "2", description: "بالمتر تعلية الدروة مع تشكيل الأعمدة بنفس الشكل القائم وملئها بالخرسانة", unit: "م.ط", quantity: 120.0, unitPrice: 650.0 },
      { code: "3", description: "بالمقطوعية أعمال مرمات البياض وتأميم حول الفتحات والبند يشمل فك الشبابيك الموجودة وتسليمها للمخازن", unit: "مقطوعية", quantity: 1.0, unitPrice: 65000.0 },
      { code: "4", description: "بالمتر الطولى أعمال بياض داخلى وخارجي للدروه مع تشكيل الأعمدة بنفس الشكل القائم وملئها بالخرسانة", unit: "م.ط", quantity: 120.0, unitPrice: 250.0 },
      { code: "5", description: "بالمتر المربع أعمال الكلادينج لزوم الواجهة", unit: "م2", quantity: 150.0, unitPrice: 2900.0 },
      { code: "6", description: "بالمقطوعية صيانة أعمال التكييفات ودفن التوصيلات", unit: "مقطوعية", quantity: 1.0, unitPrice: 30000.0 },
      { code: "7", description: "بالمقطوعية تفتيح ودفن مواسير الكهرباء  والتكييف والسباكة والتقفيل عليها بالشبك والبياض والبند يشمل السقالات وكل ما يلزم لنهو الأعمال", unit: "مقطوعية", quantity: 1.0, unitPrice: 30000.0 },
      { code: "8", description: "بالمقطوعية أعمال إزالة الرخام الموجود بالواجهه ونحت وتسوية طبقات اللصق أسفلة بالبياض أو النحت والبند يشمل السقالات وكل ما يلزم لنهو الأعمال", unit: "مقطوعية", quantity: 1.0, unitPrice: 30000.0 },
      { code: "9", description: "بالمتر المربع أعمال جرافياتو غني بالأكريليك للواجهة باللون المعتمد", unit: "م2", quantity: 450.0, unitPrice: 325.0 },
      { code: "10", description: "بالعدد توريد وتركيب أباليك مع عمل التمديدات الكهربيه", unit: "عدد", quantity: 13.0, unitPrice: 3000.0 },
      { code: "11", description: "بالمقطوعية توريد أعمال اللوفر من قطاعات  الكلادينج", unit: "مقطوعية", quantity: 1.0, unitPrice: 30000.0 },
      { code: "12", description: "بالعدد توريد وتركيب شبابيك المونيوم جرار  لزوم الواجهات مقاس 1.95 * 1.25  وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 10.0, unitPrice: 14600.0 },
      { code: "13", description: "بالعدد توريد وتركيب شبابيك المونيوم ثابت لزوم الواجهات مقاس .6*2.5 وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1.0, unitPrice: 8500.0 },
      { code: "14", description: "بالعدد توريد وتركيب شبابيك المونيوم قلاب لزوم الواجهات مقاس .8*.8 وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 4.0, unitPrice: 6300.0 },
      { code: "15", description: "بالعدد توريد وتركيب كيرتين وول بنظام Structual Glazing  لزوم فراغ السلم بمقاس تقديري 3.6 * 7.5 م 2 والبند يشمل زجاج مزدوج 6 مم ملون سيكوريت + فراغ 21.3 مم + زجاج 6 مم سيكوريت شفاف وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1.0, unitPrice: 280600.0 },
      { code: "16", description: "بالعدد توريد وتركيب باب لزوم الباب الجانبي   والبند يشمل المقابض والمفصلات  والطبلة وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1.0, unitPrice: 18600.0 },
      { code: "17", description: "بالمقطوعية توريد وتركيب رخام جالاكسي اسود لعمل برواز حول باب الإدارة مع عمل كرتبونه داخلى وخارجي", unit: "مقطوعية", quantity: 1.0, unitPrice: 25000.0 },
      { code: "18", description: "بالمقطوعية توريد وتركيب رخام جالاكسي اسود لدرج المعمل", unit: "مقطوعية", quantity: 1.0, unitPrice: 3600.0 },
      { code: "19", description: "بالعدد توريد وتركيب باب لزوم المدخل الرئيسي مقاس 1.8 * 2.25  عبارة عن 2 ضلفة مفصلي والبند يشمل ال door closer والزجاج عاكس والبند يشمل المقابض والمفصلات  والطبلة وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1.0, unitPrice: 43200.0 },
      { code: "20", description: "بالعدد توريد وتركيب كشافات 150 وات ماركة ستورم", unit: "عدد", quantity: 8.0, unitPrice: 5500.0 },
    ],
  },
  {
    projectCode: "PRJ-CARTON-STORE",
    projectName: "إنشاء مبنى مخزن الكرتون",
    contractNumber: "CTR-CARTON-STORE-2026",
    signedDate: "2026-01-03",
    contractValue: 7782230.0,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "وصف البند", unit: "الوحده", quantity: 0, unitPrice: 0 },
      { code: "2", description: "بالمقطوعية إزالة المبنى القائم مع تفكيكه وتسليمه للمخازن", unit: "مقطوعيه", quantity: 1.0, unitPrice: 75000.0 },
      { code: "3", description: "بالمتر المربع عمل مبانى مسلحه و الهيكل المعدنى ارتفاع 8 مترمع التسليح الرأسى وتملية البلوك ,والبند يشمل الحفر وعمل قاعدة الأساسات وكمرات الربط", unit: "م2", quantity: 1184.8, unitPrice: 2800.0 },
      { code: "4", description: "بالمتر المربع عمل سقف قطاع مركب من الحديد والصاج والخرسانه", unit: "م2", quantity: 520.0, unitPrice: 1750.0 },
      { code: "5", description: "بالمتر المربع عمل بياض خارجى", unit: "م2", quantity: 931.0, unitPrice: 250.0 },
      { code: "6", description: "بالمتر المربع عمل بياض داخلى", unit: "م2", quantity: 1450.0, unitPrice: 250.0 },
      { code: "7", description: "بالمتر المربع عمل جرافياتو خارجى", unit: "م2", quantity: 931.0, unitPrice: 280.0 },
      { code: "8", description: "بالمتر المربع عمل جرافياتو داخلى", unit: "م2", quantity: 1450.0, unitPrice: 280.0 },
      { code: "9", description: "بالمقطوعية توريد وتركيب أعمال الانارة والقوى  وتعديل نظام الحريق القائم والتهويه بدون الستائر الهوائية", unit: "مقطوعيه", quantity: 1.0, unitPrice: 650000.0 },
      { code: "10", description: "بالعدد توريد وتركيب باب أفراد معدنى", unit: "عدد", quantity: 2.0, unitPrice: 45000.0 },
      { code: "11", description: "بالعدد توريد وتركيب باب شطر صاج سنجل عرض 3 متر وارتفاع 4 متر", unit: "عدد", quantity: 2.0, unitPrice: 126250.0 },
      { code: "12", description: "بالمقطوعية فك الراكات من ثلاجة رقم 2 وتركيبها فى مخزن الكرتون والبند يشمل كل ما يلزم لنهو الأعمال وفقا للتصميمات التنفيذية", unit: "مقطوعيه", quantity: 1.0, unitPrice: 280000.0 },
      { code: "13", description: "بالعدد توريد وتركيب ستاره هواء كارير 120 سم(C-476)موتور واحد معدل تدفق الهواء من 9 الى 11 متر بالثانية", unit: "عدد", quantity: 2.0, unitPrice: 17680.0 },
      { code: "14", description: "بالمتر المربع صب طبقة اسكريد فوق بلاطة المخزن مع تطيسق وجهين من العزل الأسمنتى", unit: "م2", quantity: 520.0, unitPrice: 250.0 },
      { code: "15", description: "بالمتر المربع توريد وتنفيذ أرضيات خرسانة مسلحة سمك 15 سم شامل رامبات المداخل (بند إختيارى )", unit: "م2", quantity: 520.0, unitPrice: 1500.0 },
    ],
  },
  {
    projectCode: "PRJ-EXEC-FACADE",
    projectName: "تطوير الواجهة الأمامية (التنفيذية)",
    contractNumber: "CTR-EXEC-FACADE-2026",
    signedDate: "2026-02-04",
    contractValue: 725450.0,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "بالمقطوعية إزالة  الانترلوك والرخام المللى جراى وتكسير طبقة المونة أسفله وترحيل المخلفات للمقالب العمومية", unit: "مقطوعية", quantity: 1.0, unitPrice: 29800.0 },
      { code: "2", description: "بالمتر  المربع أعمال بياض خارجي للسفل", unit: "م2", quantity: 150.0, unitPrice: 250.0 },
      { code: "3", description: "بالمتر المربع توريد وتركيب الجرافياتو", unit: "م2", quantity: 150.0, unitPrice: 375.0 },
      { code: "4", description: "بالمتر المربع توريد وتركيب الكلادينح", unit: "م2", quantity: 65.0, unitPrice: 2900.0 },
      { code: "5", description: "بالمتر المربع توريد وتركيب رخام أرضيات جالاكسي اسود", unit: "م2", quantity: 15.0, unitPrice: 4800.0 },
      { code: "6", description: "بالمتر المربع توريد وتركيب رخام حوائط دبل بلاك اسود", unit: "م2", quantity: 6.0, unitPrice: 5600.0 },
      { code: "7", description: "بالعدد تركيب درج رخام", unit: "عدد", quantity: 2.0, unitPrice: 400.0 },
      { code: "8", description: "بالعدد توريد وتركيب قواطع معدنية كريتال للحواجز", unit: "عدد", quantity: 4.0, unitPrice: 35000.0 },
      { code: "9", description: "بالمتر الطولى توريد وتركيب سيكا فلكس أسفل الكلادينج", unit: "م.ط", quantity: 60.0, unitPrice: 350.0 },
      { code: "10", description: "بالعدد توريد وتركيبAccess الكتروني سوبريما موديل Bio Lite N2 والبند يشمل الكلابلات والتوصيلات", unit: "عدد", quantity: 2.0, unitPrice: 73000.0 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-2025-COLD",
    projectName: "الصيانة العامة 2025 (الثلاجات والسقف)",
    contractNumber: "CTR-MAINT-2025-COLD",
    signedDate: "2026-03-01",
    contractValue: 1220704.55,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "إزالة دهانات سقف خزان الحريق وأعمال السنفره", unit: "مقطوعية", quantity: 1.0, unitPrice: 20740.0 },
      { code: "2", description: "عزل سقف خزان الحريق بمادة سيكا توب سيل وسيكا لايت وجهين متعامدين", unit: "مقطوعية", quantity: 1.0, unitPrice: 15451.3 },
      { code: "3", description: "توريد وتركيب حليات استانلس داخل ثلاجة رقم 4 وبداية الطرقة من جهة رصيف التحميل", unit: "مقطوعية", quantity: 1.0, unitPrice: 16903.1 },
      { code: "4", description: "عمل جدار وسقف من البانل مؤقت وإعادة فكه حول الTransition", unit: "متر مسطح", quantity: 110.0, unitPrice: 207.4 },
      { code: "5", description: "توريد وتركيب وزرات سقف ثلاجة رقم 4", unit: "مقطوعية", quantity: 1.0, unitPrice: 4199.85 },
      { code: "6", description: "تركيب بانل 2غرفة علي السطح مع عمل تقطيب من الأسفل بالمونه وتركيب الأبواب", unit: "متر مسطح", quantity: 120.0, unitPrice: 259.25 },
      { code: "7", description: "توريد سيزر لتركيب الشاشات مع النقل", unit: "يومية", quantity: 2.0, unitPrice: 1244.4 },
      { code: "8", description: "تصنيع وتركيب حليات أبواب رصيف الشحن", unit: "مقطوعية", quantity: 1.0, unitPrice: 10370.0 },
      { code: "9", description: "تلاجة رقم 1وزرة", unit: "متر طولي", quantity: 89.0, unitPrice: 1244.4 },
      { code: "10", description: "تلاجة رقم 2 وزره", unit: "متر طولي", quantity: 54.0, unitPrice: 1244.4 },
      { code: "11", description: "تلاجة رقم 3 وزرة", unit: "متر طولي", quantity: 60.0, unitPrice: 1244.4 },
      { code: "12", description: "تلاجة رقم 4 وزرة", unit: "متر طولى", quantity: 72.0, unitPrice: 1244.4 },
      { code: "13", description: "تلاجة رقم 6 وزرة", unit: "متر طولي", quantity: 19.0, unitPrice: 1451.8 },
      { code: "14", description: "تعتيق ونقل البانل للرضا جميع الأيام ( كلاركات + عربيات التحميل )", unit: "مقطوعية", quantity: 1.0, unitPrice: 24369.5 },
      { code: "15", description: "إزالة مخلفات وحفريات الباركينج والشارع الخارجي وترحيل المخلفات ( عربيات + لوادر + عمالة )", unit: "مقطوعية", quantity: 1.0, unitPrice: 19288.2 },
      { code: "16", description: "صيانة الحمام الخارجي وتوريد أعمال الصحي وتوريد وتركيب باب الوميتال", unit: "مقطوعية", quantity: 1.0, unitPrice: 29658.2 },
      { code: "17", description: "صب الخرسانة بجوار مخزن الكارتون والخزان", unit: "متر مربع", quantity: 18.0, unitPrice: 1037.0 },
      { code: "18", description: "تعديل راكات ثلاجه 2", unit: "مقطوعية", quantity: 1.0, unitPrice: 53716.6 },
      { code: "19", description: "صيانة حفر الارضيات لجميع ثلاجات", unit: "مقطوعية", quantity: 1.0, unitPrice: 62012.6 },
      { code: "20", description: "توريد وتركيب بانل  15 سم لزوم عمل غرقة داخل الثلاجة مع توريد والاكسسوارات الازمة", unit: "متر مربع", quantity: 109.0, unitPrice: 2592.5 },
      { code: "21", description: "تصنيع وتوريد 3 بالتات  عينات", unit: "عدد", quantity: 3.0, unitPrice: 5185.0 },
      { code: "22", description: "توريد وتركيب حليات ووزرات وصيانة", unit: "مقطوعية", quantity: 1.0, unitPrice: 86693.2 },
      { code: "23", description: "بالمتر الطولى صب وزرة خرسانة مسلحة على رصيف التحميل", unit: "متر طولي", quantity: 83.0, unitPrice: 1555.5 },
      { code: "24", description: "بالمقطوعية نقل وعمل صيانة ودهان وتركيب مروحة وتوريد داكت فليكسبل وعدد 2 بوكس", unit: "عدد", quantity: 1.0, unitPrice: 5185.0 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-2026",
    projectName: "الصيانة العامة 2026",
    contractNumber: "CTR-MAINT-2026",
    signedDate: "2026-04-02",
    contractValue: 1328063.0,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "اعمال حريق ومحابس قبل زيارة العميل الجديد", unit: "مقطوعية", quantity: 1.0, unitPrice: 55438.0 },
      { code: "2", description: "تركيب بانل فى صالة اللإستقبال", unit: "متر مسطح", quantity: 250.0, unitPrice: 321.0 },
      { code: "3", description: "ابواب جديدة ACT + حلوق حديد+ لوب +تقطيع منشار + ملء", unit: "مقطوعية", quantity: 1.0, unitPrice: 839970.0 },
      { code: "4", description: "بالمقطوعيه أعمال تكسير وصنفرة ودهان سقف الخزان بمادة سيكا توب سيل 107", unit: "مقطوعية", quantity: 1.0, unitPrice: 31110.0 },
      { code: "5", description: "بالمقطوعيه تكسير و  فتح وتقفيل  حول الباب فى نهاية طرقة الثلاجات وتركيب لوح  فايبر", unit: "مقطوعية", quantity: 1.0, unitPrice: 20740.0 },
      { code: "6", description: "بالعدد تكسير وصب حول حلوق الثلاجات", unit: "عدد", quantity: 5.0, unitPrice: 3111.0 },
      { code: "7", description: "بالمتر الطولي توريد وتركيب جاردات لطرقة الثلاجات", unit: "متر طولي", quantity: 100.0, unitPrice: 1500.0 },
      { code: "8", description: "بالمقطوعيه توريد وتركيب بانرات ووزرات JITS", unit: "مقطوعيه", quantity: 1.0, unitPrice: 135000.0 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-OLD-24-25",
    projectName: "الصيانة العامة القديمة 2024-2025",
    contractNumber: "CTR-MAINT-OLD-24-25",
    signedDate: "2026-05-03",
    contractValue: 7059871.8,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "بالمتر المربع توريد وتركيب بانل 5 سم البكس بانل والبند يشمل أعمال تجهيز السطح وتعديل أعمال الصرف", unit: "م2", quantity: 1423.0, unitPrice: 1918.0 },
      { code: "2", description: "بالمتر المربع توريد وتركيب بانل 15 سم البكس بانل والبند يشمل أعمال تجهيز السطح وتعديل أعمال الصرف", unit: "م2", quantity: 370.0, unitPrice: 2670.0 },
      { code: "3", description: "بالمقطوعية تطوير منطقة الكرتون والبند يشمل إزالة الأرضيات وإعادة صبها بمادة هيبوكسيدك ذاتية التسوية والحوائط والأسقف والكمرات المعدنية", unit: "مقطوعية", quantity: 1.0, unitPrice: 544425.0 },
      { code: "4", description: "بالمتر المربع توريد وتنفيذ دهانات جرافياتو للأسوار والفرش بالموقع العام مع ترميم الأجزاء التالفة وإعادة البياض وإزالة السيراميك وتعديل قواعد خط الحريق", unit: "م2", quantity: 1714.0, unitPrice: 436.0 },
      { code: "5", description: "بالعدد توريد وتركيب بوابات اتوماتيكية إيطالية الصنع", unit: "عدد", quantity: 2.0, unitPrice: 163328.0 },
      { code: "6", description: "إنشاء غرفة أمن شامل التشطيبات", unit: "مقطوعية", quantity: 1.0, unitPrice: 272212.0 },
      { code: "7", description: "بالعدد إنشاء غرف الفحص من الألومنيوم", unit: "عدد", quantity: 3.0, unitPrice: 108885.0 },
      { code: "8", description: "الرصيف الخلفى أعمال الإزالة للبردورة والانترلوك وتوريد وتركيب بردورة والانترلوك والمداخل وإعادة تركيب الانترلوك وبس ويلاطة خرسانية", unit: "م.ط", quantity: 110.0, unitPrice: 1348.0 },
      { code: "9", description: "مجرى مطر على حليق الكهرباء والتطايبات مع أعمال الدهانات للفرش ومعالجة البياض وهدم فرش 3 أبواب باللون الأسود بولي يوريتان", unit: "مقطوعية", quantity: 1.0, unitPrice: 177483.0 },
      { code: "10", description: "بالعدد توريد وتركيب باب ألومنيوم لعملين executive", unit: "عدد", quantity: 1.0, unitPrice: 21777.0 },
      { code: "11", description: "بالمتر المربع بناء جدار من البلوك الأسمنتي أمام المسجد", unit: "م2", quantity: 51.9, unitPrice: 892.0 },
      { code: "12", description: "بالمتر المربع أعمال بياض الجدار أمام المسجد", unit: "م2", quantity: 105.8, unitPrice: 259.0 },
      { code: "13", description: "بالمتر المربع أعمال دهان جرافياتو الجدار أمام المسجد", unit: "م2", quantity: 105.8, unitPrice: 285.0 },
      { code: "14", description: "بالمقطوعية أعمال نقل صرف الفلتر والبند يشمل تمديد عدد 3 ماسورة بولي بكامل المسار والتكسير وبناء وعزل الفرش وتركيب مصدات معدنية", unit: "مقطوعية", quantity: 1.0, unitPrice: 94497.0 },
      { code: "15", description: "بالمقطوعية تعديل شبكات الصرف والتغذية على الواجهة الخارجية وفك ومحك المطر", unit: "مقطوعية", quantity: 1.0, unitPrice: 39613.0 },
      { code: "16", description: "بالمقطوعية أعمال الصرف وتوريد وتركيب القطع اللازمة لتركيب مواسير سريعة مشبكات", unit: "مقطوعية", quantity: 1.0, unitPrice: 14585.0 },
      { code: "17", description: "بالمقطوعية أعمال توريد وتركيب خط الصرف الخارج من غرفة الغاز للصرف العمومي والبند يشمل أعمال الصحي وإعادة الصب والانترلوك والحفر وإعادة الردم وعمل فرش غرفة من المباني والبياض والعزل والحضر والردم وتوريد وتركيب عدد 2 بوابات حماية", unit: "مقطوعية", quantity: 1.0, unitPrice: 84619.0 },
      { code: "18", description: "بالمقطوعية تعديل أعمال التكييف في الشارع الخلفي والبند يشمل فك وتركيب الأجهزة وتوريد مواسير النحاس والفريون والردم وتوريد وتركيب عدد 2 حامل معدني", unit: "مقطوعية", quantity: 1.0, unitPrice: 24369.0 },
      { code: "19", description: "توريد وتركيب شرايتك شبك سلك الواجهة الخلفية", unit: "عدد", quantity: 3.0, unitPrice: 3318.0 },
      { code: "20", description: "تعديل أرضية الكرفان والبند يشمل الأرضية الخرسانية والردم والسيراميك", unit: "مقطوعية", quantity: 1.0, unitPrice: 70101.0 },
      { code: "21", description: "بالمتر المربع توريد وتركيب رخام رمادي جالاكسي اسود للمدخل", unit: "م2", quantity: 6.8, unitPrice: 3837.0 },
      { code: "22", description: "توريد وتركيب رخام رمادي شركات الأفراد الخلفية ومدخل الكرفان", unit: "مقطوعية", quantity: 1.0, unitPrice: 7881.0 },
      { code: "23", description: "توريد وتنفيذ وصب عدد 2 رامب قطاع مركب", unit: "عدد", quantity: 2.0, unitPrice: 48013.0 },
      { code: "24", description: "إصلاح الكلادينج للبوابتين والجدار", unit: "مقطوعية", quantity: 1.0, unitPrice: 49278.0 },
      { code: "25", description: "أعمال دهانات الترازيت والشارع الخلفي", unit: "مقطوعية", quantity: 1.0, unitPrice: 15555.0 },
      { code: "26", description: "توريد وتركيب عدد 3 حلوق معدنية بزوايا للفرش استانلس الترازيت", unit: "مقطوعية", quantity: 1.0, unitPrice: 50419.0 },
      { code: "27", description: "توريد وتركيب حليات استانلس لمدخل ثلاجة 3", unit: "مقطوعية", quantity: 1.0, unitPrice: 11407.0 },
      { code: "28", description: "المتر الطولى توريد وتنفيذ وزرة خرسانية لمدخل ثلاجة 3", unit: "م.ط", quantity: 12.0, unitPrice: 1659.0 },
      { code: "29", description: "أعمال صب طبقة خرسانية إضافية للفلتر خلف المسجد", unit: "مقطوعية", quantity: 1.0, unitPrice: 25925.0 },
      { code: "30", description: "توريد الضرافيات للبوابات", unit: "مقطوعية", quantity: 1.0, unitPrice: 8400.0 },
      { code: "31", description: "توريد وتنفيذ تعديلات الموتال للموكرز الرجالي والسيدات", unit: "مقطوعية", quantity: 1.0, unitPrice: 25339.0 },
    ],
  },
  {
    projectCode: "PRJ-PRODUCTION-HALL",
    projectName: "تطوير صالة الإنتاج",
    contractNumber: "CTR-PRODUCTION-HALL-2026",
    signedDate: "2026-03-01",
    contractValue: 6373557.55,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "بالمقطوعية  أعمال فك الأبواب  وغلق الفتحات وتركيب الباب وفك السقف البلاطات الجبسية مع توريد الإكسسوارات اللازمه", unit: "مقطوعيه", quantity: 1.0, unitPrice: 42931.8 },
      { code: "2", description: "بالمقطوعية تعديل  أعمال الMEP", unit: "مقطوعيه", quantity: 1.0, unitPrice: 207400.0 },
      { code: "3", description: "بالمقطوعية تحديد بالمنشار حول فتحات المجارى مع تكسير المجارى ونقل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1.0, unitPrice: 25925.0 },
      { code: "4", description: "بالمقطوعية تكسير الجدار وصب رامب خرسانة مسلحة  مع تأميم الفتحات من البياض وضبط الرصيف حول الرامب", unit: "مقطوعيه", quantity: 1.0, unitPrice: 22399.2 },
      { code: "5", description: "بالمتر الطولى  توريد وتركيب مجري استانلس 2 مم  شامل الغطاء", unit: "م.ط", quantity: 33.5, unitPrice: 12962.5 },
      { code: "6", description: "بالمتر الطولى صب خرسانة مسلحة مكان فتحات المجارى والبند يشمل التزريع  والربط", unit: "م.ط", quantity: 52.0, unitPrice: 570.35 },
      { code: "7", description: "بالمتر الطولى صب  وزرة من الخرسانة مسلحة", unit: "م.ط", quantity: 150.0, unitPrice: 1244.4 },
      { code: "8", description: "بالمتر الطولى دهان  وزرة من الكيمابوكسي", unit: "م.ط", quantity: 150.0, unitPrice: 259.25 },
      { code: "9", description: "بالمقطوعية فك جدار صالة الجزر", unit: "مقطوعيه", quantity: 1.0, unitPrice: 14518.0 },
      { code: "10", description: "بالمقطوعية تقفيل فتحات وعمل تجليدة عمود الصالة", unit: "مقطوعيه", quantity: 1.0, unitPrice: 829.6 },
      { code: "11", description: "بالمقطوعية تقفيل الفتحات فى الجدران بين الصالة والتوسعات", unit: "مقطوعيه", quantity: 1.0, unitPrice: 1037.0 },
      { code: "12", description: "بالمقطوعية فك ونقل الجدار بين التوسعات والممر الجديد", unit: "مقطوعيه", quantity: 1.0, unitPrice: 12444.0 },
      { code: "13", description: "بالمقطوعية عمل غرفة على الرامب الجديد وتركيب باب سيكشنال", unit: "مقطوعيه", quantity: 1.0, unitPrice: 10370.0 },
      { code: "14", description: "بالمقطوعية تركيب ودهان الستارة", unit: "مقطوعيه", quantity: 1.0, unitPrice: 1555.5 },
      { code: "15", description: "بالمقطوعية تعديل مخارج الهواء والبند يشمل توريد عدد 18 مخرج جريلة المونيوم وعدد 38 بوكس من الصاج وطول 130 متر فليكسبل", unit: "مقطوعيه", quantity: 1.0, unitPrice: 185623.0 },
      { code: "16", description: "بالمتر المربع توريد وتركيب  بانل 5 سم لزوم الصالة ونفق التبريد", unit: "م2", quantity: 2200.0, unitPrice: 1814.75 },
      { code: "17", description: "بالمتر المربع توريد وتركيب  بانل 10 سم لزوم استكمال سقف الصالة وتجليد الحائط", unit: "م2", quantity: 500.0, unitPrice: 2333.25 },
    ],
  },
  {
    projectCode: "PRJ-NEW-PACKING",
    projectName: "إنشاء مبنى التعبئة الجديدة",
    contractNumber: "CTR-NEW-PACKING-2026",
    signedDate: "2026-06-01",
    contractValue: 8413953.31,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "بالمقطوعية أعمال إزالة البانل والشبابيك وتقفيل الباب وعمل تقفيل حول الباب الفاصل وفك الباب وتشوين السليم وترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1.0, unitPrice: 37332.0 },
      { code: "2", description: "بالمقطوعية أعمال إزالة البانل للتوسعه مع إزالة السندرة والجدار وعمل  جدار بانل فاصل  بين التعبئة ومنطقة العمل", unit: "مقطوعيه", quantity: 1.0, unitPrice: 32354.4 },
      { code: "3", description: "بالمقطوعية أعمال تفكيك الهيكل  المعدنى والسلم وترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1.0, unitPrice: 57035.0 },
      { code: "4", description: "بالمقطوعية أعمال تكسير وإزالة الخرسانة المسلحة والبند يشمل إزالة الأرضيات فى المستوى العلوى وترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1.0, unitPrice: 49776.0 },
      { code: "5", description: "بالمقطوعية فك أعمال الكهرباء والحريق وتعديل مواسير الهواء القائمة", unit: "مقطوعيه", quantity: 1.0, unitPrice: 31110.0 },
      { code: "6", description: "بالمتر المكعب توريد وتنفيذ أعمال ردم على طبقات", unit: "م3", quantity: 325.0, unitPrice: 544.425 },
      { code: "7", description: "بالمتر الطولى توريد وتنفيذ مواسير لزوم شبكة الصرف", unit: "م.ط", quantity: 52.0, unitPrice: 466.65 },
      { code: "8", description: "بالمتر الطولى  توريد وتركيب مجري استانلس   شامل الغطاء", unit: "م.ط", quantity: 14.0, unitPrice: 14518.0 },
      { code: "9", description: "بالعدد توريد وتركيب جاليتراب استانلس 45سم * 45 سم عمق 85 سم  شامل الغطاء", unit: "عدد", quantity: 1.0, unitPrice: 31758.125 },
      { code: "10", description: "بالعدد توريد وتنفيذ قواعد خرسانة مسلحة و رقاب الاعمده", unit: "عدد", quantity: 9.0, unitPrice: 18666.0 },
      { code: "11", description: "بالمتر المربع توريد وتنفيذ بلاطة أرضيات سمك 20 سم من الخرسانة المسلحه", unit: "م2", quantity: 384.0, unitPrice: 2281.4 },
      { code: "12", description: "بالمتر الطولى توريد وتنفيذ Upstand  من الخرسانة المسلحة", unit: "م.ط", quantity: 96.0, unitPrice: 1555.5 },
      { code: "13", description: "بالطن توريد وتنفيذ هيكل معدنى عمل دور إضافى", unit: "طن", quantity: 9.875, unitPrice: 77775.0 },
      { code: "14", description: "بالطن تعديل  وتركيب هيكل معدنى عمل دور إضافى", unit: "طن", quantity: 15.515, unitPrice: 26599.05 },
      { code: "15", description: "بالمقطوعية توريد وتركيب جوايط وبلاتات + ( نقل عدد 3 تريلات من المصنع الى قليوب والعودة )", unit: "مقطوعيه", quantity: 1.0, unitPrice: 88145.0 },
      { code: "16", description: "بالمتر المربع توريد وتنفيذ بلاطة قطاع مركب من الخرسانه والحديد", unit: "م2", quantity: 384.0, unitPrice: 1555.5 },
      { code: "17", description: "توريد وتركيب صندوق حريق استانلس للمنسوب السفلى مع ربطة بالشبكة", unit: "عدد", quantity: 1.0, unitPrice: 97996.5 },
      { code: "18", description: "أعمال كهرباء المنسوب السفلي  شامل التغذية والإنارة  واللوحات", unit: "مقطوعيه", quantity: 1.0, unitPrice: 432584.55 },
      { code: "19", description: "بالعدد توريد وتركيب   ابواب High speed  ACT أبعاد (2.5*3) م", unit: "عدد", quantity: 2.0, unitPrice: 265990.5 },
      { code: "20", description: "بالعدد توريد وتركيب  ابواب High speed  ACT أبعاد (3*3) م", unit: "عدد", quantity: 1.0, unitPrice: 307989.0 },
      { code: "21", description: "بالعدد توريد وتركيب  1 باب Shutter  شركة ATC أبعاد (3*3) م", unit: "عدد", quantity: 1.0, unitPrice: 244991.25 },
      { code: "22", description: "بالعدد تركيب لوب  بين الابواب", unit: "عدد", quantity: 2.0, unitPrice: 27999.0 },
      { code: "23", description: "بالعدد عمل غرفة تفتيش خارجية", unit: "عدد", quantity: 1.0, unitPrice: 10888.5 },
      { code: "24", description: "بالمتر المربع تعديل كلادينج الواجهة", unit: "م2", quantity: 45.4, unitPrice: 3007.3 },
      { code: "25", description: "بالمتر الطولى توريد وتركيب سيكا فلكس للكلادينج الخارجي", unit: "م.ط", quantity: 79.0, unitPrice: 362.95 },
      { code: "26", description: "بالعدد توريد وتركيب عدد 1 باب أفراد فرانس ميتال", unit: "عدد", quantity: 1.0, unitPrice: 53924.0 },
      { code: "27", description: "بالعدد تركيب سلم داخلى", unit: "عدد", quantity: 1.0, unitPrice: 311100.0 },
      { code: "28", description: "بالعدد تركيب سلم خارجي", unit: "عدد", quantity: 1.0, unitPrice: 57035.0 },
      { code: "29", description: "بالمقطوعية أعمال صبت للرصيف أمام المستلزمات وعمل عتبة خرسانية رأسية أمام الباب الشاتر ودهانها بالجرافياتو", unit: "مقطوعيه", quantity: 1.0, unitPrice: 12029.2 },
      { code: "30", description: "بالمتر المربع عزل أرضيات السقف عزل أسمنتى", unit: "م2", quantity: 384.0, unitPrice: 181.475 },
      { code: "31", description: "يالمتر المربع توريد وتركيب بانل  سم أسقف وجدران وأعمدة", unit: "م2", quantity: 1300.0, unitPrice: 1814.75 },
    ],
  },
  {
    projectCode: "PRJ-PARKING",
    projectName: "تطوير المواقف",
    contractNumber: "CTR-PARKING-2026",
    signedDate: "2026-03-12",
    contractValue: 2006242.42,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "بالعدد توريد وتركيب عدد 3 بوابات الكترونية تحكم كارت ذكى +   طول الذراع 4 م COMUNELLO ايطالى -والبند بشمل التمديد الكهربية والأعمال المدنية", unit: "عدد", quantity: 3.0, unitPrice: 137921.0 },
      { code: "2", description: "بالعدد توريد وتركيب أغطية صرف والبند يشمل التثبيت والصب حولها", unit: "عدد", quantity: 5.0, unitPrice: 12962.5 },
      { code: "3", description: "بالعدد توريد وتركيب غرفة أمن من الفايبر جلاس 1.5 م * 1.5 م مزود بعدد 2 شباك وباب الوميتال وإناره وفيشة كهرباء والأرضية شاسيه حديد مغطى بالخشب وكرسي داخلى", unit: "عدد", quantity: 1.0, unitPrice: 77775.0 },
      { code: "4", description: "بالمتر الطولى تخطيط الباركينج", unit: "م.ط", quantity: 165.0, unitPrice: 155.55 },
      { code: "5", description: "بالمتر الطولى توريد وتركيب بلدورات لزوم تحديد المواقف وأحواض الزرع ومبانى بجوار المصنع", unit: "م.ط", quantity: 162.0, unitPrice: 290.36 },
      { code: "6", description: "بالمتر الطولى توريد وتركيب بلدورات - كبيره", unit: "م.ط", quantity: 23.0, unitPrice: 362.95 },
      { code: "7", description: "بالعدد توريد زرع دورانتا و زنارى", unit: "عدد", quantity: 9000.0, unitPrice: 31.11 },
      { code: "8", description: "بالمقطوعيه توريد وتركيب حواجز معدنية وسلاسل معدنية والبند يشمل الصب والتثبيت", unit: "مقطوعية", quantity: 1.0, unitPrice: 57035.0 },
      { code: "9", description: "بالمتر المربع توريد وتركيب انتر لوك ارضيات فك القديم وترحيله للمقالب العمومية والحفر لزوم توريد رمل نظيف والدك والتسويه", unit: "م2", quantity: 1000.0, unitPrice: 544.425 },
      { code: "10", description: "بالعدد توريد وتركيب مظلات كابولية للسيارات كما هو مرفق بالرسومات والأبعاد الملحقه", unit: "عدد", quantity: 2.0, unitPrice: 243695.0 },
    ],
  },
  {
    projectCode: "PRJ-WASTE-MOSQUE",
    projectName: "مبنى المخلفات وتطوير المنطقة بجوار المسجد",
    contractNumber: "CTR-WASTE-MOSQUE-2026",
    signedDate: "2026-03-01",
    contractValue: 2940804.3,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة بديلة للنسخة السابقة.",
    boq: [
      { code: "1", description: "وصف البند", unit: "الوحده", quantity: 0, unitPrice: 0 },
      { code: "2", description: "بالمقطوعية إزالة المبنى القائم مع تفكيكه ( البانل + الصاج + الحديد )", unit: "مقطوعيه", quantity: 1.0, unitPrice: 46665.0 },
      { code: "3", description: "بالمقطوعية أعمال تكسير البلاطات الخرسانية القائمة  المائلة بكامل مسطح  وحفر القواعد الخرسانية  مع ترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1.0, unitPrice: 46665.0 },
      { code: "4", description: "بالعدد صب قواعد من الخرسانة المسلحة لزوم أعمال الأساسات", unit: "عدد", quantity: 7.0, unitPrice: 10370.0 },
      { code: "5", description: "بالمتر المربع أعمال مبانى من الطوب الأسمنتى", unit: "م2", quantity: 407.0, unitPrice: 622.2 },
      { code: "6", description: "بالعدد توريد وصب أعمدة خرسانية مسلحة", unit: "عدد", quantity: 7.0, unitPrice: 7777.5 },
      { code: "7", description: "بالعدد صب كمرة خرسانية مسلحة فى الجدار الخلفي", unit: "عدد", quantity: 1.0, unitPrice: 9333.0 },
      { code: "8", description: "بالمتر المربع عمل بياض", unit: "م2", quantity: 831.0, unitPrice: 259.25 },
      { code: "9", description: "بالمتر المربع عمل جرافياتو داخلى + خارجى", unit: "م2", quantity: 891.0, unitPrice: 290.36 },
      { code: "10", description: "بالمتر المربع توريد وتركيب سقف معدنى كمرات + مدادات مع الصاج 0.7 جلفنة 180", unit: "م2", quantity: 140.0, unitPrice: 1711.05 },
      { code: "11", description: "بالمتر الطولى توريد وتنفيذ رقبة زجاجة داخلية وخارجية وعلى السطح", unit: "م.ط", quantity: 116.0, unitPrice: 93.33 },
      { code: "12", description: "بالعدد توريد وتركيب باب شطر صاج سنجل سمك 0.8 عرض 3 متر بموتور ايطالى Nice", unit: "عدد", quantity: 2.0, unitPrice: 82960.0 },
      { code: "13", description: "بالمتر المربع توريد وتنفيذ أرضيات خرسانة مسلحة سمك 20 سم  لزوم الأرضيات داخل وحول المبنى", unit: "م2", quantity: 250.0, unitPrice: 1866.6 },
      { code: "14", description: "بالمتر الطولى توريد وتركيب مجارى الأرضيات والبند يشمل الأغطية وغرفتي التفتيش ومواسير الربط بالغرفة العمومية", unit: "م.ط", quantity: 50.0, unitPrice: 1037.0 },
      { code: "15", description: "بالمقطوعية أعمال الكهرباء", unit: "مقطوعيه", quantity: 1.0, unitPrice: 153994.5 },
      { code: "16", description: "بالمقطوعية أعمال الحريق", unit: "مقطوعيه", quantity: 1.0, unitPrice: 254065.0 },
      { code: "17", description: "بالمقطوعية أعمال توصيل المياه", unit: "مقطوعيه", quantity: 1.0, unitPrice: 6222.0 },
      { code: "18", description: "بالمقطوعية توريد وتركيب بوابات عدد 4 بوابات", unit: "مقطوعيه", quantity: 1.0, unitPrice: 365000.0 },
      { code: "19", description: "بالمقطوعية توريد وتركيب عدد 3  موتور", unit: "عدد", quantity: 3.0, unitPrice: 48998.25 },
      { code: "20", description: "بالمقطوعية عمل مرمات بياض السور", unit: "مقطوعيه", quantity: 1.0, unitPrice: 10370.0 },
      { code: "21", description: "بالمتر المربع دهان جرافياتو للأسوار", unit: "م2", quantity: 113.0, unitPrice: 290.36 },
      { code: "22", description: "بالمتر الطولى أعمال عزل السطح", unit: "م.ط", quantity: 48.0, unitPrice: 362.95 },
      { code: "23", description: "بالمتر الطولى أعمال مجري المطر", unit: "م.ط", quantity: 12.0, unitPrice: 1037.0 },
      { code: "24", description: "بالمتر الطولي عمل كاب من الجرافياتو الاسود", unit: "م.ط", quantity: 78.0, unitPrice: 290.36 },
      { code: "25", description: "بالمتر الطولي دهان تخطيط الارضيات", unit: "مقطوعيه", quantity: 1.0, unitPrice: 16592.0 },
      { code: "26", description: "بالمقطوعية إستكمال الرصيف بجوار السور", unit: "مقطوعيه", quantity: 1.0, unitPrice: 10370.0 },
    ],
  },
];