// بيانات العقود العشرة — نسخة استبدال ثالثة (2026-07-29)، مستخرجة من ملفات PDF جديدة
// كل عقد اتحقق منه رياضيًا: مجموع كل بنود جدول الكميات = الإجمالي المطبوع في العقد بالظبط
// العقود اللي وصف بنودها اتغيّر هيكليًا عن النسخة السابقة (الصيانة 2025، الصيانة 2026، الصيانة القديمة)
// اتسجلت ببند إجمالي واحد بس (القيمة موثّقة ومتحقق منها، لكن التفصيل الكامل لكل بند محتاج مراجعة نسخة العقد الأصلية)

export const CLIENT_DATA = {
  name: "رايه فودز",
  address: "66 ر 11 المنطقة الصناعية الأولى - مدينة السادات (تجميد وتعبئة المواد الغذائية)",
  notes: "سجل تجاري رقم 17002 استثمار القاهرة",
};

type BoqRow = { code: string; description: string; unit: string; quantity: number; unitPrice: number };

export type ContractSeed = {
  projectCode: string;
  projectName: string;
  contractNumber: string;
  signedDate: string;
  contractValue: number;
  advancePaymentPct: number;
  notes: string;
  boq: BoqRow[];
};

export const CONTRACTS_SEED_V3: ContractSeed[] = [
  {
    projectCode: "PRJ-ADMIN-FACADE",
    projectName: "إحلال وتجديد واجهة مبنى الإدارة",
    contractNumber: "CTR-ADMIN-FACADE-2026",
    signedDate: "2026-03-01",
    contractValue: 1459300,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "بالمقطوعية إزالة الجرافياتو والبياض المفكك والبند يشمل السقالات وكل ما يلزم لنهو الأعمال", unit: "مقطوعية", quantity: 1, unitPrice: 17000 },
      { code: "2", description: "بالمتر تعلية الدروة مع تشكيل الأعمدة بنفس الشكل القائم وملئها بالخرسانة", unit: "م.ط", quantity: 86, unitPrice: 650 },
      { code: "3", description: "بالمقطوعية أعمال مرمات البياض وتأميم حول الفتحات والبند يشمل فك الشبابيك الموجودة وتسليمها للمخازن", unit: "مقطوعية", quantity: 1, unitPrice: 65000 },
      { code: "4", description: "بالمتر الطولى أعمال بياض داخلى وخارجي للدروه مع تشكيل الأعمدة بنفس الشكل القائم وملئها بالخرسانة", unit: "م.ط", quantity: 86, unitPrice: 250 },
      { code: "5", description: "بالمتر المربع أعمال الكلادينج لزوم الواجهة", unit: "م2", quantity: 148, unitPrice: 2900 },
      { code: "6", description: "بالمقطوعية صيانة أعمال التكييفات ودفن التوصيلات", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "7", description: "بالمقطوعية تفتيح ودفن مواسير الكهرباء  والتكييف والسباكة والتقفيل عليها بالشبك والبياض والبند يشمل السقالات وكل ما يلزم لنهو الأعمال", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "8", description: "بالمقطوعية أعمال إزالة الرخام الموجود بالواجهه ونحت وتسوية طبقات اللصق أسفلة بالبياض أو النحت والبند يشمل السقالات وكل ما يلزم لنهو الأعمال", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "9", description: "بالمتر المربع أعمال جرافياتو غني بالأكريليك للواجهة باللون المعتمد", unit: "م2", quantity: 360, unitPrice: 325 },
      { code: "10", description: "بالعدد توريد وتركيب أباليك مع عمل التمديدات الكهربيه", unit: "عدد", quantity: 13, unitPrice: 3000 },
      { code: "11", description: "بالمقطوعية توريد أعمال اللوفر من قطاعات  الكلادينج", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "12", description: "بالعدد توريد وتركيب شبابيك المونيوم جرار  لزوم الواجهات مقاس 1.95 * 1.25  وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 10, unitPrice: 14600 },
      { code: "13", description: "بالعدد توريد وتركيب شبابيك المونيوم ثابت لزوم الواجهات مقاس .6*2.5 وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1, unitPrice: 8500 },
      { code: "14", description: "بالعدد توريد وتركيب شبابيك المونيوم قلاب لزوم الواجهات مقاس .8*.8 وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 4, unitPrice: 6300 },
      { code: "15", description: "بالعدد توريد وتركيب كيرتين وول بنظام Structual Glazing  لزوم فراغ السلم بمقاس تقديري 3.6 * 7.5 م 2 والبند يشمل زجاج مزدوج 6 مم ملون سيكوريت + فراغ 21.3 مم + زجاج 6 مم سيكوريت شفاف وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1, unitPrice: 280600 },
      { code: "16", description: "بالعدد توريد وتركيب باب لزوم الباب الجانبي   والبند يشمل المقابض والمفصلات  والطبلة وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1, unitPrice: 18600 },
      { code: "17", description: "بالمقطوعية توريد وتركيب رخام جالاكسي اسود لعمل برواز حول باب الإدارة مع عمل كرتبونه داخلى وخارجي", unit: "مقطوعية", quantity: 1, unitPrice: 25000 },
      { code: "18", description: "بالمقطوعية توريد وتركيب رخام جالاكسي اسود لدرج المعمل", unit: "مقطوعية", quantity: 1, unitPrice: 3600 },
      { code: "19", description: "بالعدد توريد وتركيب باب لزوم المدخل الرئيسي مقاس 1.8 * 2.25  عبارة عن 2 ضلفة مفصلي والبند يشمل ال door closer والزجاج عاكس والبند يشمل المقابض والمفصلات  والطبلة وكل ما يلزم لنهو الاعمال", unit: "عدد", quantity: 1, unitPrice: 43200 },
      { code: "20", description: "بالعدد توريد وتركيب كشافات 150 وات ماركة ستورم", unit: "عدد", quantity: 8, unitPrice: 5500 },
    ],
  },
  {
    projectCode: "PRJ-CARTON-STORE",
    projectName: "إنشاء مبنى مخزن الكرتون",
    contractNumber: "CTR-CARTON-STORE-2026",
    signedDate: "2026-01-03",
    contractValue: 7445070,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "بند رقم 1 (راجع نسخة العقد الأصلية للوصف الكامل)", unit: "بند", quantity: 1, unitPrice: 75000 },
      { code: "2", description: "بالمقطوعية إزالة المبنى القائم مع تفكيكه وتسليمه للمخازن", unit: "مقطوعيه", quantity: 1184.8, unitPrice: 2800 },
      { code: "3", description: "بالمتر المربع عمل مبانى مسلحه و الهيكل المعدنى ارتفاع 8 مترمع التسليح الرأسى وتملية البلوك ,والبند يشمل الحفر وعمل قاعدة الأساسات وكمرات الربط", unit: "م2", quantity: 480, unitPrice: 1750 },
      { code: "4", description: "بالمتر المربع عمل سقف قطاع مركب من الحديد والصاج والخرسانه", unit: "م2", quantity: 931, unitPrice: 250 },
      { code: "5", description: "بالمتر المربع عمل بياض خارجى", unit: "م2", quantity: 1078, unitPrice: 250 },
      { code: "6", description: "بالمتر المربع عمل بياض داخلى", unit: "م2", quantity: 931, unitPrice: 280 },
      { code: "7", description: "بالمتر المربع عمل جرافياتو خارجى", unit: "م2", quantity: 1078, unitPrice: 280 },
      { code: "8", description: "بالمتر المربع عمل جرافياتو داخلى", unit: "م2", quantity: 1, unitPrice: 650000 },
      { code: "9", description: "بالمقطوعية توريد وتركيب أعمال الانارة والقوى  وتعديل نظام الحريق القائم والتهويه بدون الستائر الهوائية", unit: "مقطوعيه", quantity: 2, unitPrice: 45000 },
      { code: "10", description: "بالعدد توريد وتركيب باب أفراد معدنى", unit: "عدد", quantity: 2, unitPrice: 126250 },
      { code: "11", description: "بالعدد توريد وتركيب باب شطر صاج سنجل عرض 3 متر وارتفاع 4 متر", unit: "عدد", quantity: 1, unitPrice: 280000 },
      { code: "12", description: "بالمقطوعية فك الراكات من ثلاجة رقم 2 وتركيبها فى مخزن الكرتون والبند يشمل كل ما يلزم لنهو الأعمال وفقا للتصميمات التنفيذية", unit: "مقطوعيه", quantity: 2, unitPrice: 17680 },
      { code: "13", description: "بالعدد توريد وتركيب ستاره هواء كارير 120 سم(C-476)موتور واحد معدل تدفق الهواء من 9 الى 11 متر بالثانية", unit: "عدد", quantity: 480, unitPrice: 250 },
      { code: "14", description: "بالمتر المربع صب طبقة اسكريد فوق بلاطة المخزن مع تطيسق وجهين من العزل الأسمنتى", unit: "م2", quantity: 480, unitPrice: 1500 },
    ],
  },
  {
    projectCode: "PRJ-EXEC-FACADE",
    projectName: "تطوير الواجهة الأمامية (التنفيذية)",
    contractNumber: "CTR-EXEC-FACADE-2026",
    signedDate: "2026-02-04",
    contractValue: 663325,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "بالمقطوعية إزالة  الانترلوك والرخام المللى جراى وتكسير طبقة المونة أسفله وترحيل المخلفات للمقالب العمومية", unit: "مقطوعية", quantity: 1, unitPrice: 29800 },
      { code: "2", description: "بالمتر  المربع أعمال بياض خارجي للسفل", unit: "م2", quantity: 97, unitPrice: 250 },
      { code: "3", description: "بالمتر المربع توريد وتركيب الجرافياتو", unit: "م2", quantity: 97, unitPrice: 375 },
      { code: "4", description: "بالمتر المربع توريد وتركيب الكلادينح", unit: "م2", quantity: 55, unitPrice: 2900 },
      { code: "5", description: "بالمتر المربع توريد وتركيب رخام أرضيات جالاكسي اسود", unit: "م2", quantity: 15, unitPrice: 4800 },
      { code: "6", description: "بالمتر المربع توريد وتركيب رخام حوائط دبل بلاك اسود", unit: "م2", quantity: 6, unitPrice: 5600 },
      { code: "7", description: "بالعدد تركيب درج رخام", unit: "عدد", quantity: 2, unitPrice: 400 },
      { code: "8", description: "بالعدد توريد وتركيب قواطع معدنية كريتال للحواجز", unit: "عدد", quantity: 4, unitPrice: 35000 },
      { code: "9", description: "بالمتر الطولى توريد وتركيب سيكا فلكس أسفل الكلادينج", unit: "م.ط", quantity: 60, unitPrice: 350 },
      { code: "10", description: "بالعدد توريد وتركيبAccess الكتروني سوبريما موديل Bio Lite N2 والبند يشمل الكلابلات والتوصيلات", unit: "عدد", quantity: 2, unitPrice: 73000 },
    ],
  },
  {
    projectCode: "PRJ-PRODUCTION-HALL",
    projectName: "تطوير صالة الإنتاج",
    contractNumber: "CTR-PRODUCTION-HALL-2026",
    signedDate: "2026-03-01",
    contractValue: 6050450,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "بالمقطوعية  أعمال فك الأبواب  وغلق الفتحات وتركيب الباب وفك السقف البلاطات الجبسية مع توريد الإكسسوارات اللازمه", unit: "مقطوعيه", quantity: 1, unitPrice: 41400 },
      { code: "2", description: "بالمقطوعية تعديل  أعمال الMEP", unit: "مقطوعيه", quantity: 1, unitPrice: 200000 },
      { code: "3", description: "بالمقطوعية تحديد بالمنشار حول فتحات المجارى مع تكسير المجارى ونقل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1, unitPrice: 25000 },
      { code: "4", description: "بالمقطوعية تكسير الجدار وصب رامب خرسانة مسلحة  مع تأميم الفتحات من البياض وضبط الرصيف حول الرامب", unit: "مقطوعيه", quantity: 1, unitPrice: 21600 },
      { code: "5", description: "بالمتر الطولى  توريد وتركيب مجري استانلس 2 مم  شامل الغطاء", unit: "م.ط", quantity: 33.5, unitPrice: 12500 },
      { code: "6", description: "بالمتر الطولى صب خرسانة مسلحة مكان فتحات المجارى والبند يشمل التزريع  والربط", unit: "م.ط", quantity: 52, unitPrice: 550 },
      { code: "7", description: "بالمتر الطولى صب  وزرة من الخرسانة مسلحة", unit: "م.ط", quantity: 84, unitPrice: 1200 },
      { code: "8", description: "بالمتر الطولى دهان  وزرة من الكيمابوكسي", unit: "م.ط", quantity: 84, unitPrice: 250 },
      { code: "9", description: "بالمقطوعية فك جدار صالة الجزر", unit: "مقطوعيه", quantity: 1, unitPrice: 14000 },
      { code: "10", description: "بالمقطوعية تقفيل فتحات وعمل تجليدة عمود الصالة", unit: "مقطوعيه", quantity: 1, unitPrice: 800 },
      { code: "11", description: "بالمقطوعية تقفيل الفتحات فى الجدران بين الصالة والتوسعات", unit: "مقطوعيه", quantity: 1, unitPrice: 1000 },
      { code: "12", description: "بالمقطوعية فك ونقل الجدار بين التوسعات والممر الجديد", unit: "مقطوعيه", quantity: 1, unitPrice: 12000 },
      { code: "13", description: "بالمقطوعية عمل غرفة على الرامب الجديد وتركيب باب سيكشنال", unit: "مقطوعيه", quantity: 1, unitPrice: 10000 },
      { code: "14", description: "بالمقطوعية تركيب ودهان الستارة", unit: "مقطوعيه", quantity: 1, unitPrice: 1500 },
      { code: "15", description: "بالمقطوعية تعديل مخارج الهواء والبند يشمل توريد عدد 18 مخرج جريلة المونيوم وعدد 38 بوكس من الصاج وطول 130 متر فليكسبل", unit: "مقطوعيه", quantity: 1, unitPrice: 179000 },
      { code: "16", description: "بالمتر المربع توريد وتركيب  بانل 5 سم لزوم الصالة ونفق التبريد", unit: "م2", quantity: 2200, unitPrice: 1750 },
      { code: "17", description: "بالمتر المربع توريد وتركيب  بانل 10 سم لزوم استكمال سقف الصالة وتجليد الحائط", unit: "م2", quantity: 500, unitPrice: 2250 },
    ],
  },
  {
    projectCode: "PRJ-NEW-PACKING",
    projectName: "إنشاء مبنى التعبئة الجديدة",
    contractNumber: "CTR-NEW-PACKING-2026",
    signedDate: "2026-06-01",
    contractValue: 7633944.75,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "بالمقطوعية أعمال إزالة البانل والشبابيك وتقفيل الباب وعمل تقفيل حول الباب الفاصل وفك الباب وتشوين السليم وترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1, unitPrice: 36000 },
      { code: "2", description: "بالمقطوعية أعمال إزالة البانل للتوسعه مع إزالة السندرة والجدار وعمل  جدار بانل فاصل  بين التعبئة ومنطقة العمل", unit: "مقطوعيه", quantity: 1, unitPrice: 31200 },
      { code: "3", description: "بالمقطوعية أعمال تفكيك الهيكل  المعدنى والسلم وترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1, unitPrice: 55000 },
      { code: "4", description: "بالمقطوعية أعمال تكسير وإزالة الخرسانة المسلحة والبند يشمل إزالة الأرضيات فى المستوى العلوى وترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 1, unitPrice: 48000 },
      { code: "5", description: "بالمقطوعية فك أعمال الكهرباء والحريق وتعديل مواسير الهواء القائمة", unit: "مقطوعيه", quantity: 1, unitPrice: 30000 },
      { code: "6", description: "بالمتر المكعب توريد وتنفيذ أعمال ردم على طبقات", unit: "م3", quantity: 325, unitPrice: 525 },
      { code: "7", description: "بالمتر الطولى توريد وتنفيذ مواسير لزوم شبكة الصرف", unit: "م.ط", quantity: 52, unitPrice: 450 },
      { code: "8", description: "بالمتر الطولى  توريد وتركيب مجري استانلس   شامل الغطاء", unit: "م.ط", quantity: 14, unitPrice: 14000 },
      { code: "9", description: "بالعدد توريد وتركيب جاليتراب استانلس 45سم * 45 سم عمق 85 سم  شامل الغطاء", unit: "عدد", quantity: 1, unitPrice: 30625 },
      { code: "10", description: "بالعدد توريد وتنفيذ قواعد خرسانة مسلحة و رقاب الاعمده", unit: "عدد", quantity: 9, unitPrice: 18000 },
      { code: "11", description: "بالمتر المربع توريد وتنفيذ بلاطة أرضيات سمك 20 سم من الخرسانة المسلحه", unit: "م2", quantity: 325, unitPrice: 2200 },
      { code: "12", description: "بالمتر الطولى توريد وتنفيذ Upstand  من الخرسانة المسلحة", unit: "م.ط", quantity: 96, unitPrice: 1500 },
      { code: "13", description: "بالطن توريد وتنفيذ هيكل معدنى عمل دور إضافى", unit: "طن", quantity: 9.875, unitPrice: 75000 },
      { code: "14", description: "بالطن تعديل  وتركيب هيكل معدنى عمل دور إضافى", unit: "طن", quantity: 25650, unitPrice: 15.515 },
      { code: "15", description: "بالمقطوعية توريد وتركيب جوايط وبلاتات + ( نقل عدد 3 تريلات من المصنع الى قليوب والعودة )", unit: "مقطوعيه", quantity: 1, unitPrice: 85000 },
      { code: "16", description: "بالمتر المربع توريد وتنفيذ بلاطة قطاع مركب من الخرسانه والحديد", unit: "م2", quantity: 384, unitPrice: 1500 },
      { code: "17", description: "توريد وتركيب صندوق حريق استانلس للمنسوب السفلى مع ربطة بالشبكة", unit: "عدد", quantity: 1, unitPrice: 94500 },
      { code: "18", description: "أعمال كهرباء المنسوب السفلي  شامل التغذية والإنارة  واللوحات", unit: "مقطوعيه", quantity: 1, unitPrice: 417150 },
      { code: "19", description: "بالعدد توريد وتركيب   ابواب High speed  ACT أبعاد (2.5*3) م", unit: "عدد", quantity: 2, unitPrice: 256500 },
      { code: "20", description: "بالعدد توريد وتركيب  ابواب High speed  ACT أبعاد (3*3) م", unit: "عدد", quantity: 1, unitPrice: 297000 },
      { code: "21", description: "بالعدد توريد وتركيب  1 باب Shutter  شركة ATC أبعاد (3*3) م", unit: "عدد", quantity: 1, unitPrice: 236250 },
      { code: "22", description: "بالعدد تركيب لوب  بين الابواب", unit: "عدد", quantity: 2, unitPrice: 27000 },
      { code: "23", description: "بالعدد عمل غرفة تفتيش خارجية", unit: "عدد", quantity: 1, unitPrice: 10500 },
      { code: "24", description: "بالمتر المربع تعديل كلادينج الواجهة", unit: "م2", quantity: 45.4, unitPrice: 2900 },
      { code: "25", description: "بالمتر الطولى توريد وتركيب سيكا فلكس للكلادينج الخارجي", unit: "م.ط", quantity: 79, unitPrice: 350 },
      { code: "26", description: "بالعدد توريد وتركيب عدد 1 باب أفراد فرانس ميتال", unit: "عدد", quantity: 1, unitPrice: 52000 },
      { code: "27", description: "بالعدد تركيب سلم داخلى", unit: "عدد", quantity: 1, unitPrice: 300000 },
      { code: "28", description: "بالعدد تركيب سلم خارجي", unit: "عدد", quantity: 1, unitPrice: 55000 },
      { code: "29", description: "بالمقطوعية أعمال صبت للرصيف أمام المستلزمات وعمل عتبة خرسانية رأسية أمام الباب الشاتر ودهانها بالجرافياتو", unit: "مقطوعيه", quantity: 1, unitPrice: 11600 },
      { code: "30", description: "بالمتر المربع عزل أرضيات السقف عزل أسمنتى", unit: "م2", quantity: 384, unitPrice: 175 },
      { code: "31", description: "يالمتر المربع توريد وتركيب بانل  سم أسقف وجدران وأعمدة", unit: "م2", quantity: 1100, unitPrice: 1750 },
    ],
  },
  {
    projectCode: "PRJ-PARKING",
    projectName: "تطوير المواقف",
    contractNumber: "CTR-PARKING-2026",
    signedDate: "2026-03-12",
    contractValue: 1934660,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "بالعدد توريد وتركيب عدد 3 بوابات الكترونية تحكم كارت ذكى +   طول الذراع 4 م COMUNELLO ايطالى -والبند بشمل التمديد الكهربية والأعمال المدنية", unit: "عدد", quantity: 3, unitPrice: 133000 },
      { code: "2", description: "بالعدد توريد وتركيب أغطية صرف والبند يشمل التثبيت والصب حولها", unit: "عدد", quantity: 5, unitPrice: 12500 },
      { code: "3", description: "بالعدد توريد وتركيب غرفة أمن من الفايبر جلاس 1.5 م * 1.5 م مزود بعدد 2 شباك وباب الوميتال وإناره وفيشة كهرباء والأرضية شاسيه حديد مغطى بالخشب وكرسي داخلى", unit: "عدد", quantity: 1, unitPrice: 75000 },
      { code: "4", description: "بالمتر الطولى تخطيط الباركينج", unit: "م.ط", quantity: 165, unitPrice: 150 },
      { code: "5", description: "بالمتر الطولى توريد وتركيب بلدورات لزوم تحديد المواقف وأحواض الزرع ومبانى بجوار المصنع", unit: "م.ط", quantity: 162, unitPrice: 280 },
      { code: "6", description: "بالمتر الطولى توريد وتركيب بلدورات - كبيره", unit: "م.ط", quantity: 23, unitPrice: 350 },
      { code: "7", description: "بالعدد توريد زرع دورانتا و زنارى", unit: "عدد", quantity: 9000, unitPrice: 30 },
      { code: "8", description: "بالمقطوعيه توريد وتركيب حواجز معدنية وسلاسل معدنية والبند يشمل الصب والتثبيت", unit: "مقطوعية", quantity: 1, unitPrice: 55000 },
      { code: "9", description: "بالمتر المربع توريد وتركيب انتر لوك ارضيات فك القديم وترحيله للمقالب العمومية والحفر لزوم توريد رمل نظيف والدك والتسويه", unit: "م2", quantity: 1000, unitPrice: 525 },
      { code: "10", description: "بالعدد توريد وتركيب مظلات كابولية للسيارات كما هو مرفق بالرسومات والأبعاد الملحقه", unit: "عدد", quantity: 2, unitPrice: 235000 },
    ],
  },
  {
    projectCode: "PRJ-WASTE-MOSQUE",
    projectName: "مبنى المخلفات وتطوير المنطقة بجوار المسجد",
    contractNumber: "CTR-WASTE-MOSQUE-2026",
    signedDate: "2026-03-01",
    contractValue: 2789150,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "بند رقم 1 (راجع نسخة العقد الأصلية للوصف الكامل)", unit: "بند", quantity: 1, unitPrice: 45000 },
      { code: "2", description: "بالمقطوعية إزالة المبنى القائم مع تفكيكه ( البانل + الصاج + الحديد )", unit: "مقطوعيه", quantity: 1, unitPrice: 45000 },
      { code: "3", description: "بالمقطوعية أعمال تكسير البلاطات الخرسانية القائمة  المائلة بكامل مسطح  وحفر القواعد الخرسانية  مع ترحيل المخلفات للمقالب العمومية", unit: "مقطوعيه", quantity: 7, unitPrice: 10000 },
      { code: "4", description: "بالعدد صب قواعد من الخرسانة المسلحة لزوم أعمال الأساسات", unit: "عدد", quantity: 407, unitPrice: 600 },
      { code: "5", description: "بالمتر المربع أعمال مبانى من الطوب الأسمنتى", unit: "م2", quantity: 7, unitPrice: 7500 },
      { code: "6", description: "بالعدد توريد وصب أعمدة خرسانية مسلحة", unit: "عدد", quantity: 1, unitPrice: 9000 },
      { code: "7", description: "بالعدد صب كمرة خرسانية مسلحة فى الجدار الخلفي", unit: "عدد", quantity: 831, unitPrice: 250 },
      { code: "8", description: "بالمتر المربع عمل بياض", unit: "م2", quantity: 891, unitPrice: 280 },
      { code: "9", description: "بالمتر المربع عمل جرافياتو داخلى + خارجى", unit: "م2", quantity: 140, unitPrice: 1650 },
      { code: "10", description: "بالمتر المربع توريد وتركيب سقف معدنى كمرات + مدادات مع الصاج 0.7 جلفنة 180", unit: "م2", quantity: 116, unitPrice: 90 },
      { code: "11", description: "بالمتر الطولى توريد وتنفيذ رقبة زجاجة داخلية وخارجية وعلى السطح", unit: "م.ط", quantity: 2, unitPrice: 80000 },
      { code: "12", description: "بالعدد توريد وتركيب باب شطر صاج سنجل سمك 0.8 عرض 3 متر بموتور ايطالى Nice", unit: "عدد", quantity: 250, unitPrice: 1800 },
      { code: "13", description: "بالمتر المربع توريد وتنفيذ أرضيات خرسانة مسلحة سمك 20 سم  لزوم الأرضيات داخل وحول المبنى", unit: "م2", quantity: 50, unitPrice: 1000 },
      { code: "14", description: "بالمتر الطولى توريد وتركيب مجارى الأرضيات والبند يشمل الأغطية وغرفتي التفتيش ومواسير الربط بالغرفة العمومية", unit: "م.ط", quantity: 1, unitPrice: 148500 },
      { code: "15", description: "بالمقطوعية أعمال الكهرباء", unit: "مقطوعيه", quantity: 1, unitPrice: 245000 },
      { code: "16", description: "بالمقطوعية أعمال الحريق", unit: "مقطوعيه", quantity: 1, unitPrice: 6000 },
      { code: "17", description: "بالمقطوعية أعمال توصيل المياه", unit: "مقطوعيه", quantity: 1, unitPrice: 303750 },
      { code: "18", description: "بالمقطوعية توريد وتركيب بوابات عدد 4 بوابات", unit: "مقطوعيه", quantity: 3, unitPrice: 47250 },
      { code: "19", description: "بالمقطوعية توريد وتركيب عدد 3  موتور", unit: "عدد", quantity: 1, unitPrice: 10000 },
      { code: "20", description: "بالمقطوعية عمل مرمات بياض السور", unit: "مقطوعيه", quantity: 1, unitPrice: 31640 },
      { code: "21", description: "بالمتر المربع دهان جرافياتو للأسوار", unit: "م2", quantity: 48, unitPrice: 350 },
      { code: "22", description: "بالمتر الطولى أعمال عزل السطح", unit: "م.ط", quantity: 12, unitPrice: 1000 },
      { code: "23", description: "بالمتر الطولى أعمال مجري المطر", unit: "م.ط", quantity: 78, unitPrice: 280 },
      { code: "24", description: "بالمتر الطولي عمل كاب من الجرافياتو الاسود", unit: "م.ط", quantity: 1, unitPrice: 16000 },
      { code: "25", description: "بالمتر الطولي دهان تخطيط الارضيات", unit: "مقطوعيه", quantity: 1, unitPrice: 1500 },
      { code: "26", description: "بالمقطوعية إستكمال الرصيف بجوار السور", unit: "مقطوعيه", quantity: 1, unitPrice: 10000 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-2025-COLD",
    projectName: "الصيانة العامة 2025 (الثلاجات والسقف)",
    contractNumber: "CTR-MAINT-2025-COLD",
    signedDate: "2026-03-01",
    contractValue: 1115650,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "إجمالي أعمال العقد — الصيانة العامة 2025 (الثلاجات والسقف) (راجع نسخة العقد الأصلية للتفصيل الكامل لكل بند)", unit: "مقطوعية", quantity: 1, unitPrice: 1115650 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-2026",
    projectName: "الصيانة العامة 2026",
    contractNumber: "CTR-MAINT-2026",
    signedDate: "2026-04-02",
    contractValue: 1076922,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "إجمالي أعمال العقد — الصيانة العامة 2026 (راجع نسخة العقد الأصلية للتفصيل الكامل لكل بند)", unit: "مقطوعية", quantity: 1, unitPrice: 1076922 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-OLD-24-25",
    projectName: "الصيانة العامة القديمة 2024-2025",
    contractNumber: "CTR-MAINT-OLD-24-25",
    signedDate: "2026-05-03",
    contractValue: 6543384,
    advancePaymentPct: 30,
    notes: "دفعة مقدمة 30% تُخصم من كل مستخلص. نسخة عقد مُحدَّثة ثالثة (استبدال) بتاريخ 2026-07-29.",
    boq: [
      { code: "1", description: "إجمالي أعمال العقد — الصيانة العامة القديمة 2024-2025 (راجع نسخة العقد الأصلية للتفصيل الكامل لكل بند)", unit: "مقطوعية", quantity: 1, unitPrice: 6543384 },
    ],
  },
];