// بيانات العقود العشرة الفعلية بين Section General Contracting وشركة رايه فودز
// تم استخراجها من ملفات PDF ومراجعة إجمالي كل عقد للتأكد من مطابقته للمجموع المذكور في المستند

export const CLIENT_DATA = {
  name: "رايه فودز",
  address: "66 ر 11 المنطقة الصناعية الأولى - مدينة السادات (تجميد وتعبئة المواد الغذائية)",
  notes: "سجل تجاري رقم 17002 استثمار القاهرة — يمثلها المهندس عمر خالد محمود عبد العزيز",
};

type BoqRow = { code: string; description: string; unit: string; quantity: number; unitPrice: number };

export type ContractSeed = {
  projectCode: string;
  projectName: string;
  contractNumber: string;
  signedDate: string; // YYYY-MM-DD
  contractValue: number;
  advancePaymentPct: number;
  notes: string;
  boq: BoqRow[];
};

export const CONTRACTS_SEED: ContractSeed[] = [
  {
    projectCode: "PRJ-ADMIN-FACADE",
    projectName: "إحلال وتجديد واجهة مبنى الإدارة",
    contractNumber: "CTR-ADMIN-FACADE-2026",
    signedDate: "2026-03-01",
    contractValue: 1459300,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد — لا يوجد نص صريح على نسبة ضمان حسن تنفيذ في العقد.",
    boq: [
      { code: "1", description: "إزالة الجرافياتو والبياض الممكك والبند يشمل السقالات وكل ما يلزم لنحو الأعمال", unit: "مقطوعية", quantity: 1, unitPrice: 17000 },
      { code: "2", description: "تعلية الدروة مع تشكيل الأعمدة بنفس الشكل القائم وملئها بالخرسانة", unit: "م.ط", quantity: 86, unitPrice: 650 },
      { code: "3", description: "أعمال مرمات البياض وتأمين حول الفتحات الموجودة وتسليمها للمخازن", unit: "مقطوعية", quantity: 1, unitPrice: 65000 },
      { code: "4", description: "أعمال بياض داخلي وخارجي بنفس الشكل القائم", unit: "م.ط", quantity: 86, unitPrice: 250 },
      { code: "5", description: "أعمال الكلادينج لزوم الواجهة", unit: "م2", quantity: 148, unitPrice: 2900 },
      { code: "6", description: "صيانة أعمال التكييفات ودفن التوصيلات", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "7", description: "تفتيت ودفن مواسير الكهرباء والسباكة والتقنين بالشبك والبياض", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "8", description: "إزالة الرخام الموجود بالواجهة ونحت وتسوية طبقات اللصق", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "9", description: "أعمال جرافياتو غني بالأكريليك للواجهة باللون المعتمد", unit: "م2", quantity: 360, unitPrice: 325 },
      { code: "10", description: "توريد وتركيب أباليك مع عمل التمديدات الكهربية", unit: "عدد", quantity: 13, unitPrice: 3000 },
      { code: "11", description: "توريد أعمال اللوفر من قطاعات الكلادينج", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "12", description: "توريد وتركيب شبابيك ألومنيوم جرار لزوم الواجهات مقاس 1.95×1.25", unit: "عدد", quantity: 10, unitPrice: 14600 },
      { code: "13", description: "توريد وتركيب شبابيك ألومنيوم ثابت لزوم الواجهات مقاس 6×2.5", unit: "عدد", quantity: 1, unitPrice: 8500 },
      { code: "14", description: "توريد وتركيب قلاب ألومنيوم شبابيك لزوم الواجهات مقاس 8×6", unit: "عدد", quantity: 4, unitPrice: 6300 },
      { code: "15", description: "نظام Structural Glazing لفراغ السلم — زجاج مزدوج 6مم سيكوريت + فراغ 21.3مم + زجاج 6مم سيكوريت شفاف", unit: "عدد", quantity: 1, unitPrice: 280600 },
      { code: "16", description: "توريد وتركيب باب الجانبي شامل المقابض والمصلات والطبلات", unit: "عدد", quantity: 1, unitPrice: 18600 },
      { code: "17", description: "توريد وتركيب رخام جالاكسي أسود حول باب الإدارة مع كرتيبونة داخلي وخارجي", unit: "مقطوعية", quantity: 1, unitPrice: 25000 },
      { code: "18", description: "توريد وتركيب رخام جالاكسي أسود لدرج المعمل", unit: "مقطوعية", quantity: 1, unitPrice: 3600 },
      { code: "19", description: "توريد وتركيب باب المدخل الرئيسي مقاس 1.8×2.25 مضلع مع closer door وزجاج عاكس", unit: "عدد", quantity: 1, unitPrice: 43200 },
      { code: "20", description: "توريد وتركيب كشافات 150 وات ماركة ستوريك", unit: "عدد", quantity: 8, unitPrice: 5500 },
    ],
  },
  {
    projectCode: "PRJ-CARTON-STORE",
    projectName: "إنشاء مبنى مخزن الكرتون",
    contractNumber: "CTR-CARTON-STORE-2026",
    signedDate: "2026-04-01",
    contractValue: 7445070,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "إزالة المبنى القائم مع تفكيكه وتسليمه للمخازن", unit: "مقطوعية", quantity: 1, unitPrice: 75000 },
      { code: "2", description: "عمل مباني مسلحة والهيكل المعدني ارتفاع 8م مع التسليح الرأسي وتمليط البلوك، شامل الحفر وقاعدة الأساسات وكمرات الربط", unit: "م2", quantity: 1184.8, unitPrice: 2800 },
      { code: "3", description: "عمل سقف قطاع مركب من الحديد والصاج والخرسانة", unit: "م2", quantity: 480, unitPrice: 1750 },
      { code: "4", description: "عمل بياض خارجي", unit: "م2", quantity: 931, unitPrice: 250 },
      { code: "5", description: "عمل بياض داخلي", unit: "م2", quantity: 1078, unitPrice: 250 },
      { code: "6", description: "عمل جرافياتو خارجي", unit: "م2", quantity: 931, unitPrice: 280 },
      { code: "7", description: "عمل جرافياتو داخلي", unit: "م2", quantity: 1078, unitPrice: 280 },
      { code: "8", description: "توريد وتركيب أعمال الإنارة والقوى وتعديل نظام الحريق القائم والتهوية (بدون الستائر الهوائية)", unit: "مقطوعية", quantity: 1, unitPrice: 650000 },
      { code: "9", description: "توريد وتركيب باب أفراد معدني", unit: "عدد", quantity: 2, unitPrice: 45000 },
      { code: "10", description: "توريد وتركيب باب شطر صاج سنجل عرض 3م وارتفاع 4م", unit: "عدد", quantity: 2, unitPrice: 126250 },
      { code: "11", description: "فك الراكات من ثلاجة رقم 2 وتركيبها في مخزن الكرتون", unit: "مقطوعية", quantity: 1, unitPrice: 280000 },
      { code: "12", description: "توريد وتركيب ستارة هواء كارير 120 سم — معدل تدفق الهواء 9-11 م/ث", unit: "عدد", quantity: 2, unitPrice: 17680 },
      { code: "13", description: "صب طبقة إسكريد فوق بلاطة المخزن مع وجهين من العزل الأسمنتي", unit: "م2", quantity: 480, unitPrice: 250 },
      { code: "14", description: "توريد وتنفيذ أرضيات خرسانة مسلحة سمك 15 سم شامل رامبات المداخل (بند اختياري)", unit: "م2", quantity: 480, unitPrice: 1500 },
    ],
  },
  {
    projectCode: "PRJ-EXEC-FACADE",
    projectName: "تطوير الواجهة الأمامية (التنفيذية)",
    contractNumber: "CTR-EXEC-FACADE-2026",
    signedDate: "2026-03-01",
    contractValue: 663325,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "إزالة الإنترلوك والرخام الملي جراء وتكسير طبقة المونة أسفله وترحيل المخلفات", unit: "مقطوعية", quantity: 1, unitPrice: 29800 },
      { code: "2", description: "أعمال بياض خارجي للسفل", unit: "م2", quantity: 97, unitPrice: 250 },
      { code: "3", description: "توريد وتركيب جرافياتو", unit: "م2", quantity: 97, unitPrice: 375 },
      { code: "4", description: "توريد وتركيب كلادينج", unit: "م2", quantity: 55, unitPrice: 2900 },
      { code: "5", description: "توريد وتركيب أرضيات رخام جالاكسي أسود", unit: "م2", quantity: 15, unitPrice: 4800 },
      { code: "6", description: "توريد وتركيب رخام حوائط ديب بلاك أسود", unit: "م2", quantity: 6, unitPrice: 5600 },
      { code: "7", description: "تركيب درج رخام", unit: "عدد", quantity: 2, unitPrice: 400 },
      { code: "8", description: "توريد وتركيب قواطع معدنية للحواجز", unit: "عدد", quantity: 4, unitPrice: 35000 },
      { code: "9", description: "توريد وتركيب سيكا فلكس أسفل الكلادينج", unit: "م.ط", quantity: 60, unitPrice: 350 },
      { code: "10", description: "توريد وتركيب Access إلكتروني سوبريما موديل Bio Lite N2 شامل الكابلات والتوصيلات", unit: "عدد", quantity: 2, unitPrice: 73000 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-2025-COLD",
    projectName: "الصيانة العامة 2025 (الثلاجات والسقف)",
    contractNumber: "CTR-MAINT-2025-COLD",
    signedDate: "2026-03-01",
    contractValue: 1115650,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "إزالة دهانات سقف خزان الحريق وأعمال السنفرة", unit: "مقطوعية", quantity: 1, unitPrice: 20000 },
      { code: "2", description: "عزل سقف خزان الحريق بمادة سيكا توب سيل ولايت وجهين متعامدين", unit: "مقطوعية", quantity: 1, unitPrice: 14900 },
      { code: "3", description: "توريد وتركيب حليات استانلس داخل ثلاجة رقم 4 وبداية الطرقة من رصيف التحميل", unit: "مقطوعية", quantity: 1, unitPrice: 16300 },
      { code: "4", description: "عمل جدار وسقف من البانل مؤقت وإعادة فكه حول الـ Transition", unit: "م.مسطح", quantity: 68, unitPrice: 200 },
      { code: "5", description: "توريد وتركيب وزرات سقف ثلاجة رقم 4", unit: "مقطوعية", quantity: 1, unitPrice: 4050 },
      { code: "6", description: "تركيب بانل بغرفتين على السطح مع تقطيب من الأسفل بالمونة وتركيب الأبواب", unit: "م.مسطح", quantity: 90, unitPrice: 250 },
      { code: "7", description: "توريد سيزر لترتيب الشاشات مع النقل", unit: "يومية", quantity: 2, unitPrice: 1200 },
      { code: "8", description: "تصنيع وتركيب حليات أبواب رصيف الشحن", unit: "مقطوعية", quantity: 1, unitPrice: 10000 },
      { code: "9", description: "وزرة ثلاجة رقم 1", unit: "م.ط", quantity: 49.8, unitPrice: 1200 },
      { code: "10", description: "وزرة ثلاجة رقم 2", unit: "م.ط", quantity: 19, unitPrice: 1200 },
      { code: "11", description: "وزرة ثلاجة رقم 3", unit: "م.ط", quantity: 37.9, unitPrice: 1200 },
      { code: "12", description: "وزرة ثلاجة رقم 4", unit: "م.ط", quantity: 38.3, unitPrice: 1200 },
      { code: "13", description: "وزرة ثلاجة رقم 6", unit: "م.ط", quantity: 5, unitPrice: 1400 },
      { code: "14", description: "توريد وتركيب وحدات الأرشيف وتعديل القاعدة الحديدية ودهان الغرفة وتوريد كشاف إضاءة", unit: "مقطوعية", quantity: 1, unitPrice: 130000 },
      { code: "15", description: "نقل وتعتيق البانل لجميع الأيام (كلاركات + عربيات التحميل)", unit: "مقطوعية", quantity: 1, unitPrice: 23500 },
      { code: "16", description: "إزالة مخلفات وحفريات الباركينج والشارع الخارجي وترحيل المخلفات", unit: "مقطوعية", quantity: 1, unitPrice: 18600 },
      { code: "17", description: "صيانة الحمام الخارجي وتوريد أعمال الصحي وتوريد وتركيب باب الوميتال", unit: "مقطوعية", quantity: 1, unitPrice: 28600 },
      { code: "18", description: "صب الخرسانة بجوار مخزن الكرتون والخزان", unit: "م2", quantity: 18, unitPrice: 1000 },
      { code: "19", description: "تعديل راكات ثلاجة 2 (وليد)", unit: "مقطوعية", quantity: 1, unitPrice: 51800 },
      { code: "20", description: "صيانة حصر الأرضيات لجميع الثلاجات", unit: "مقطوعية", quantity: 1, unitPrice: 59800 },
      { code: "21", description: "توريد وتركيب بانل 15 سم لعمل غرفة داخل الثلاجات شامل الإكسسوارات", unit: "م2", quantity: 109, unitPrice: 2500 },
      { code: "22", description: "تصنيع وتوريد 3 بلنتات عينات", unit: "عدد", quantity: 3, unitPrice: 5000 },
      { code: "23", description: "توريد وتركيب حليات ووزرات وصيانة قبل الزيارة", unit: "مقطوعية", quantity: 1, unitPrice: 83600 },
      { code: "24", description: "توريد وتركيب باب بليسيه على السطح — مبنى الأدمن", unit: "عدد", quantity: 1, unitPrice: 0 },
      { code: "25", description: "صب وزرة خرسانة مسلحة على رصيف التحميل", unit: "م.ط", quantity: 83, unitPrice: 1500 },
      { code: "26", description: "نقل وعمل صيانة ودهان مروحة وتوريد داكت فليكسبيل وعدد 2 بوكس", unit: "عدد", quantity: 1, unitPrice: 5000 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-2026",
    projectName: "الصيانة العامة 2026",
    contractNumber: "CTR-MAINT-2026",
    signedDate: "2026-03-01",
    contractValue: 1076922,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "دفعات بإذارات سيد صالة الإنتاج (50.000)", unit: "مقطوعية", quantity: 1, unitPrice: 67500 },
      { code: "2", description: "أعمال حريق ومحابس قبل زيارة العميل الجديد", unit: "مقطوعية", quantity: 1, unitPrice: 53460 },
      { code: "3", description: "تراخيص باركينج مهندس طارق (50.000)", unit: "مقطوعية", quantity: 1, unitPrice: 67500 },
      { code: "4", description: "تقارير دفاع مدني", unit: "مقطوعية", quantity: 1, unitPrice: 33750 },
      { code: "5", description: "تركيب بانل في صالة الاستقبال", unit: "م.مسطح", quantity: 144, unitPrice: 310.5 },
      { code: "6", description: "أبواب جديدة ACT حديد + لوب + تقطيع منشار + ملء", unit: "مقطوعية", quantity: 1, unitPrice: 810000 },
      { code: "7", description: "أعمال تكسير وصنفرة ودهان سقف الخزان بمادة سيكا توب سيل 107", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "8", description: "فتح وتقفيل حول الباب في نهاية طرقة الثلاجات وتركيب لوح فايبر", unit: "مقطوعية", quantity: 1, unitPrice: 20000 },
      { code: "9", description: "تكسير وصب حول حلوق الثلاجات", unit: "عدد", quantity: 5, unitPrice: 3000 },
    ],
  },
  {
    projectCode: "PRJ-MAINT-OLD-24-25",
    projectName: "الصيانة العامة القديمة 2024-2025",
    contractNumber: "CTR-MAINT-OLD-24-25",
    signedDate: "2026-03-01",
    contractValue: 6543384,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "إزالة الجراسيات والبياض الممكك شامل السقالات وتجهيز السطح ومعدات الصرف", unit: "م2", quantity: 1280, unitPrice: 1850 },
      { code: "2", description: "توريد وتركيب بانل 15 سم شامل تجهيز السطح وتعديل أعمال الصرف", unit: "م2", quantity: 370, unitPrice: 2575 },
      { code: "3", description: "تطوير منطقة الكرتون — إزالة الأرضيات وإعادة التسوية ذاتية للحوائط والأسقف والكمرات المعدنية", unit: "مقطوعية", quantity: 1, unitPrice: 525000 },
      { code: "4", description: "توريد وتنفيذ دهانات جرافياتو للأسوار والغرف الفرعية مع ترميم الأجزاء التالفة وإعادة البياض وتعديل قواعد خط الحريق", unit: "م2", quantity: 1714, unitPrice: 420 },
      { code: "5", description: "توريد وتركيب بوابات أوتوماتيكية إبطالها الصنع", unit: "عدد", quantity: 2, unitPrice: 157500 },
      { code: "6", description: "إنشاء غرفة أمن شامل أعمال التشطيبات", unit: "مقطوعية", quantity: 1, unitPrice: 262500 },
      { code: "7", description: "توريد غرف الضص من الألومنيوم", unit: "عدد", quantity: 3, unitPrice: 105000 },
      { code: "8", description: "الرصيف الخلفي — إزالة البلدورة والانترلوك وتوريد وتركيب انترلوك جديد وردم وخرسانة وبلاط", unit: "م.ط", quantity: 110, unitPrice: 1300 },
      { code: "9", description: "مجري مطر لغرفة الكهرباء والنفايات مع دهانات الغرفة ومعالجة البياض باللون الأسود بوريتان", unit: "مقطوعية", quantity: 1, unitPrice: 171150 },
      { code: "10", description: "توريد وتركيب باب ألومنيوم لمبنى الإكتيف", unit: "عدد", quantity: 1, unitPrice: 21000 },
      { code: "11", description: "بناء جدار من البلوك أمام المسجد", unit: "م2", quantity: 51.9, unitPrice: 860 },
      { code: "12", description: "أعمال بياض حائط أمام المسجد", unit: "م2", quantity: 105.8, unitPrice: 250 },
      { code: "13", description: "أعمال دهان جرافياتو الجدار أمام المسجد", unit: "م2", quantity: 105.8, unitPrice: 275 },
      { code: "14", description: "أعمال نقل صرف الفلتر شامل تمديد 3 مواسير والتكسير والبياض وعزل غطاء الصرف", unit: "مقطوعية", quantity: 1, unitPrice: 91125 },
      { code: "15", description: "تعديل مواسير الصرف والتغذية على الواجهة الخارجية", unit: "مقطوعية", quantity: 1, unitPrice: 38200 },
      { code: "16", description: "أعمال صحي وتركيب قطع لمضخات شبكات الصرف في غرفة الغاز", unit: "مقطوعية", quantity: 1, unitPrice: 14065 },
      { code: "17", description: "خط الصرف من غرفة الغاز للصرف العمومي شامل تكسير الخرسانة وإعادة الردم وبوابة حماية", unit: "مقطوعية", quantity: 1, unitPrice: 81600 },
      { code: "18", description: "تعديل أعمال التكييف والشراع الخلفي شامل الأجهزة ومواسير النحاس والريون", unit: "مقطوعية", quantity: 1, unitPrice: 23500 },
      { code: "19", description: "توريد وتركيب شبابيك ضاف سلك الواجهة الخلفية", unit: "عدد", quantity: 3, unitPrice: 3200 },
      { code: "20", description: "تعديل أرضيات الكرفان شامل الأرضيات الخرسانية والردم والسيراميك", unit: "مقطوعية", quantity: 1, unitPrice: 67600 },
      { code: "21", description: "توريد وتركيب رخام جالاكسي أسود للمدخل", unit: "م2", quantity: 6.8, unitPrice: 3700 },
      { code: "22", description: "توريد وتركيب رخام رمادي لأبواب الأفراد الخلفية ومدخل الكرفان", unit: "مقطوعية", quantity: 1, unitPrice: 7600 },
      { code: "23", description: "صب قطاع 2 رامب لأبواب الأفراد الخلفية والمدخل", unit: "عدد", quantity: 2, unitPrice: 46300 },
      { code: "24", description: "إصلاح الكلادينج للبوابتين والجدار", unit: "مقطوعية", quantity: 1, unitPrice: 47320 },
      { code: "25", description: "أعمال دهانات الترازيت والشارع الخلفي", unit: "مقطوعية", quantity: 1, unitPrice: 15000 },
      { code: "26", description: "توريد وتركيب حليات 3 معدنية بزوايا مغلطة لغرفة استانلس الترازيت", unit: "مقطوعية", quantity: 1, unitPrice: 48620 },
      { code: "27", description: "توريد وتركيب حليات استانلس لمدخل ثلاجة 3", unit: "مقطوعية", quantity: 1, unitPrice: 11000 },
      { code: "28", description: "توريد وتنفيذ وزرة خرسانة لمدخل ثلاجة 3", unit: "م.ط", quantity: 12, unitPrice: 1600 },
      { code: "29", description: "صب طبقة خرسانة إضافية للفلتر خلف المسجد", unit: "مقطوعية", quantity: 1, unitPrice: 25000 },
      { code: "30", description: "تعديل تصريفات البيوتات", unit: "مقطوعية", quantity: 1, unitPrice: 8100 },
      { code: "31", description: "توريد وتنفيذ تعديلات الموتال للمطبخ الرجالي والسيدات", unit: "مقطوعية", quantity: 1, unitPrice: 24435 },
    ],
  },
  {
    projectCode: "PRJ-NEW-PACKING",
    projectName: "إنشاء مبنى التعبئة الجديدة",
    contractNumber: "CTR-NEW-PACKING-2026",
    signedDate: "2026-05-01",
    contractValue: 7633945,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "إزالة الباب والشبابيك وتقفيل الباب الفاصل وفك الباب السليم وتشوين المخلفات", unit: "مقطوعية", quantity: 1, unitPrice: 36000 },
      { code: "2", description: "إزالة البانل للتوسعة مع إزالة السندرة وعمل جدار بانل فاصل", unit: "مقطوعية", quantity: 1, unitPrice: 31200 },
      { code: "3", description: "تفكيك الهيكل المعدني والسلم وترحيل المخلفات", unit: "مقطوعية", quantity: 1, unitPrice: 55000 },
      { code: "4", description: "تكسير وإزالة الخرسانة المسلحة شامل الأرضيات في المستوى العلوي", unit: "مقطوعية", quantity: 1, unitPrice: 48000 },
      { code: "5", description: "فك أعمال الكهرباء والحريق وتعديل مواسير الهواء القائمة", unit: "مقطوعية", quantity: 1, unitPrice: 30000 },
      { code: "6", description: "أعمال ردم على طبقات", unit: "م3", quantity: 325, unitPrice: 525 },
      { code: "7", description: "توريد وتنفيذ مواسير لزوم شبكة الصرف", unit: "م.ط", quantity: 52, unitPrice: 450 },
      { code: "8", description: "توريد وتركيب مجري استانلس شامل الغطاء", unit: "م.ط", quantity: 14, unitPrice: 14000 },
      { code: "9", description: "توريد وتركيب جالبيرات استانلس 45×45 سم عمق 85 سم شامل الغطاء", unit: "عدد", quantity: 1, unitPrice: 30625 },
      { code: "10", description: "توريد وتنفيذ قواعد خرسانة مسلحة ورقاب الأعمدة", unit: "عدد", quantity: 9, unitPrice: 18000 },
      { code: "11", description: "توريد وتنفيذ أرضيات بلاطة سمك 20 سم من الخرسانة المسلحة", unit: "م2", quantity: 325, unitPrice: 2200 },
      { code: "12", description: "توريد وتنفيذ Upstand من الخرسانة المسلحة", unit: "م.ط", quantity: 96, unitPrice: 1500 },
      { code: "13", description: "توريد وتنفيذ هيكل معدني لعمل دور إضافي", unit: "طن", quantity: 9.875, unitPrice: 75000 },
      { code: "14", description: "تعديل وتركيب هيكل معدني لعمل دور إضافي", unit: "طن", quantity: 15.515, unitPrice: 25650 },
      { code: "15", description: "توريد وتركيب جوايط وبلاطات (نقل تريلات من المصنع لقليوب والعودة)", unit: "مقطوعية", quantity: 1, unitPrice: 85000 },
      { code: "16", description: "توريد وتنفيذ بلاطة مركب من قطاع الحديد والخرسانة", unit: "م2", quantity: 384, unitPrice: 1500 },
      { code: "17", description: "توريد وتركيب صندوق حريق استانلس للمنسوب السفلي مع ربطة بالشبكة", unit: "عدد", quantity: 1, unitPrice: 94500 },
      { code: "18", description: "أعمال كهرباء المنسوب السفلي شامل الإنارة والتغذية واللوحات", unit: "مقطوعية", quantity: 1, unitPrice: 417150 },
      { code: "19", description: "توريد وتركيب أبواب ACT High speed أبعاد 3×2.5م", unit: "عدد", quantity: 2, unitPrice: 256500 },
      { code: "20", description: "توريد وتركيب أبواب ACT High speed أبعاد 3×3م", unit: "عدد", quantity: 1, unitPrice: 297000 },
      { code: "21", description: "توريد وتركيب باب Shutter شركة ATC أبعاد 3×3م", unit: "عدد", quantity: 1, unitPrice: 236250 },
      { code: "22", description: "تركيب لوب بين الأبواب", unit: "عدد", quantity: 2, unitPrice: 27000 },
      { code: "23", description: "عمل غرفة تفتيش خارجية", unit: "عدد", quantity: 1, unitPrice: 10500 },
      { code: "24", description: "تعديل كلادينج الواجهة", unit: "م2", quantity: 45.4, unitPrice: 2900 },
      { code: "25", description: "توريد وتركيب سيكا فلكس للكلادينج الخارجي", unit: "م.ط", quantity: 79, unitPrice: 350 },
      { code: "26", description: "توريد وتركيب باب أفراد فرانس ميتال", unit: "عدد", quantity: 1, unitPrice: 52000 },
      { code: "27", description: "تركيب سلم داخلي", unit: "عدد", quantity: 1, unitPrice: 300000 },
      { code: "28", description: "تركيب سلم خارجي", unit: "عدد", quantity: 1, unitPrice: 55000 },
      { code: "29", description: "صب الرصيف أمام المستلزمات وعمل عتبة خرسانية رأسية أمام الباب الشتار مع دهانات جرافياتو", unit: "مقطوعية", quantity: 1, unitPrice: 11600 },
      { code: "30", description: "عزل أرضيات السقف — عزل أسمنتي", unit: "م2", quantity: 384, unitPrice: 175 },
      { code: "31", description: "توريد وتركيب بانل سمك 15 سم أسقف وجدران وأعمدة", unit: "م2", quantity: 1100, unitPrice: 1750 },
    ],
  },
  {
    projectCode: "PRJ-PARKING",
    projectName: "تطوير المواقف",
    contractNumber: "CTR-PARKING-2026",
    signedDate: "2026-03-01",
    contractValue: 1934660,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "توريد وتركيب 3 بوابات إلكترونية تحكم كارت ذكي + طول الذراع 4م Comunello إيطالي شامل التمديد الكهربية والمدنية", unit: "عدد", quantity: 3, unitPrice: 133000 },
      { code: "2", description: "توريد وتركيب أغطية صرف شامل التثبيت والصب حولها", unit: "عدد", quantity: 5, unitPrice: 12500 },
      { code: "3", description: "توريد وتركيب غرفة أمن من الفايبر جلاس 1.5×1.5م مزودة بشباكين وباب ألوميتال وإنارة وفيشة كهرباء", unit: "عدد", quantity: 1, unitPrice: 75000 },
      { code: "4", description: "تخطيط الباركينج", unit: "م.ط", quantity: 165, unitPrice: 150 },
      { code: "5", description: "توريد وتركيب بلدورات لتحديد المواقف وأحواض الزرع ومباني بجوار المصنع", unit: "م.ط", quantity: 162, unitPrice: 280 },
      { code: "6", description: "توريد وتركيب بلدورات كبيرة", unit: "م.ط", quantity: 23, unitPrice: 350 },
      { code: "7", description: "توريد زرع دورانتا وزناري", unit: "عدد", quantity: 9000, unitPrice: 30 },
      { code: "8", description: "توريد وتركيب حواجز معدنية وسلاسل معدنية شامل الصب والتثبيت", unit: "مقطوعية", quantity: 1, unitPrice: 55000 },
      { code: "9", description: "توريد وتركيب انترلوك أرضيات وفك القديم وترحيله مع الحفر والدك والتسوية", unit: "م2", quantity: 1000, unitPrice: 525 },
      { code: "10", description: "توريد وتركيب مظلات كابولية للسيارات", unit: "عدد", quantity: 2, unitPrice: 235000 },
    ],
  },
  {
    projectCode: "PRJ-PRODUCTION-HALL",
    projectName: "تطوير صالة الإنتاج",
    contractNumber: "CTR-PRODUCTION-HALL-2026",
    signedDate: "2026-04-01",
    contractValue: 6050450,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "فك الأبواب وغلق الفتحات وتركيب الباب وفك سقف البلاطات الجبسية شامل الإكسسوارات", unit: "مقطوعية", quantity: 1, unitPrice: 41400 },
      { code: "2", description: "تعديل أعمال MEP", unit: "مقطوعية", quantity: 1, unitPrice: 200000 },
      { code: "3", description: "تحديد بالمنشار حول فتحات المجاري مع التكسير والنقل للمقالب العمومية", unit: "مقطوعية", quantity: 1, unitPrice: 25000 },
      { code: "4", description: "تكسير الجدار رامب وصب جدار خرساني مسلح مع تأمين الفتحات والرصيف حول الرامب", unit: "مقطوعية", quantity: 1, unitPrice: 21600 },
      { code: "5", description: "توريد وتركيب مجري استانلس 2 متر شامل الغطاء", unit: "م.ط", quantity: 33.5, unitPrice: 12500 },
      { code: "6", description: "صب خرسانة مسلحة مكان فتحات المجاري شامل التسريع والربط", unit: "م.ط", quantity: 52, unitPrice: 550 },
      { code: "7", description: "صب وزرة من الخرسانة المسلحة", unit: "م.ط", quantity: 84, unitPrice: 1200 },
      { code: "8", description: "دهان وزرة من الكيمابوكسي", unit: "م.ط", quantity: 84, unitPrice: 250 },
      { code: "9", description: "فك جدار صالة الجزر", unit: "مقطوعية", quantity: 1, unitPrice: 14000 },
      { code: "10", description: "تقفيل فتحات وعمل تجليدة عمود الصالة", unit: "مقطوعية", quantity: 1, unitPrice: 800 },
      { code: "11", description: "تقفيل الفتحات في الجدران بين الصالة والتوسعات", unit: "مقطوعية", quantity: 1, unitPrice: 1000 },
      { code: "12", description: "فك ونقل الجدار بين التوسعات والممر الجديد", unit: "مقطوعية", quantity: 1, unitPrice: 12000 },
      { code: "13", description: "عمل غرفة على الرامب الجديد وتركيب باب سيكشنال", unit: "مقطوعية", quantity: 1, unitPrice: 10000 },
      { code: "14", description: "تركيب ودهان الستارة", unit: "مقطوعية", quantity: 1, unitPrice: 1500 },
      { code: "15", description: "تعديل مخارج الهواء شامل توريد 18 مخرج جريلة ألومنيوم و38 بوكس صاج و130م فليكسبيل", unit: "مقطوعية", quantity: 1, unitPrice: 179000 },
      { code: "16", description: "توريد وتركيب بانل 5 سم لزوم الصالة ونفق التبريد", unit: "م2", quantity: 2200, unitPrice: 1750 },
      { code: "17", description: "توريد وتركيب بانل 10 سم لاستكمال سقف الصالة وتجليد الحائط", unit: "م2", quantity: 500, unitPrice: 2250 },
    ],
  },
  {
    projectCode: "PRJ-WASTE-MOSQUE",
    projectName: "مبنى المخلفات وتطوير المنطقة بجوار المسجد",
    contractNumber: "CTR-WASTE-MOSQUE-2026",
    signedDate: "2026-03-01",
    contractValue: 2789150,
    advancePaymentPct: 60,
    notes: "غرامة تأخير 200 ج.م/يوم بحد أقصى 5% من قيمة العقد.",
    boq: [
      { code: "1", description: "إزالة المبنى القائم مع تفكيكه (بانل + صاج + حديد)", unit: "مقطوعية", quantity: 1, unitPrice: 45000 },
      { code: "2", description: "تكسير البلاطات الخرسانية المائلة وحفر القواعد وترحيل المخلفات", unit: "مقطوعية", quantity: 1, unitPrice: 45000 },
      { code: "3", description: "صب قواعد من الخرسانة المسلحة لزوم الأساسات", unit: "عدد", quantity: 7, unitPrice: 10000 },
      { code: "4", description: "أعمال مباني من الطوب الأسمنتي", unit: "م2", quantity: 407, unitPrice: 600 },
      { code: "5", description: "توريد وصب أعمدة خرسانية مسلحة", unit: "عدد", quantity: 7, unitPrice: 7500 },
      { code: "6", description: "صب كمرة خرسانية مسلحة في الجدار الخلفي", unit: "عدد", quantity: 1, unitPrice: 9000 },
      { code: "7", description: "عمل بياض", unit: "م2", quantity: 831, unitPrice: 250 },
      { code: "8", description: "عمل جرافياتو داخلي وخارجي", unit: "م2", quantity: 891, unitPrice: 280 },
      { code: "9", description: "توريد وتركيب سقف معدني كمرات ومدادات مع صاج 0.7 جلفنة 180", unit: "م2", quantity: 140, unitPrice: 1650 },
      { code: "10", description: "توريد وتنفيذ رقبة زجاجة داخلية وخارجية وعلى السطح", unit: "م.ط", quantity: 116, unitPrice: 90 },
      { code: "11", description: "توريد وتركيب باب شطر صاج سنجل سمك 0.8 عرض 3م بموتور إيطالي Nice", unit: "عدد", quantity: 2, unitPrice: 80000 },
      { code: "12", description: "توريد وتنفيذ أرضيات خرسانة مسلحة سمك 20 سم داخل وحول المبنى", unit: "م2", quantity: 250, unitPrice: 1800 },
      { code: "13", description: "توريد وتركيب مجاري الأرضيات شامل الأغطية وغرفتي التفتيش والربط", unit: "م.ط", quantity: 50, unitPrice: 1000 },
      { code: "14", description: "أعمال الكهرباء", unit: "مقطوعية", quantity: 1, unitPrice: 148500 },
      { code: "15", description: "أعمال الحريق", unit: "مقطوعية", quantity: 1, unitPrice: 245000 },
      { code: "16", description: "أعمال توصيل المياه", unit: "مقطوعية", quantity: 1, unitPrice: 6000 },
      { code: "17", description: "توريد وتركيب بوابات منزلقة (3 بوابات)", unit: "مقطوعية", quantity: 1, unitPrice: 303750 },
      { code: "18", description: "توريد وتركيب 3 موتور للبوابات", unit: "عدد", quantity: 3, unitPrice: 47250 },
      { code: "19", description: "عمل مرمات بياض السور", unit: "مقطوعية", quantity: 1, unitPrice: 10000 },
      { code: "20", description: "دهان جرافياتو للأسوار", unit: "م2", quantity: 113, unitPrice: 280 },
      { code: "21", description: "أعمال عزل السطح", unit: "م.ط", quantity: 48, unitPrice: 350 },
      { code: "22", description: "أعمال مجري المطر", unit: "م.ط", quantity: 12, unitPrice: 1000 },
      { code: "23", description: "عمل كاب من الجرافياتو الأسود", unit: "م.ط", quantity: 78, unitPrice: 280 },
      { code: "24", description: "دهان تخطيط الأرضيات", unit: "مقطوعية", quantity: 1, unitPrice: 16000 },
      { code: "25", description: "توريد وتركيب جرجورة صرف المطر", unit: "عدد", quantity: 1, unitPrice: 1500 },
      { code: "26", description: "استكمال الرصيف بجوار السور", unit: "مقطوعية", quantity: 1, unitPrice: 10000 },
    ],
  },
];
